CREATE TABLE users (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),

    email NVARCHAR(255) NOT NULL UNIQUE,

    password_hash NVARCHAR(255) NOT NULL,

    role NVARCHAR(30) NOT NULL DEFAULT 'admin',

    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),

    updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
