// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"hello/internal/audit"
	"hello/internal/database/sqlc"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAuditService creates a new instance of MockAuditService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditService {
	mock := &MockAuditService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditService is an autogenerated mock type for the AuditService type
type MockAuditService struct {
	mock.Mock
}

type MockAuditService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditService) EXPECT() *MockAuditService_Expecter {
	return &MockAuditService_Expecter{mock: &_m.Mock}
}

// Log provides a mock function for the type MockAuditService
func (_mock *MockAuditService) Log(ctx context.Context, params audit.LogParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Log")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, audit.LogParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditService_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type MockAuditService_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
//   - ctx context.Context
//   - params audit.LogParams
func (_e *MockAuditService_Expecter) Log(ctx any, params any) *MockAuditService_Log_Call {
	return &MockAuditService_Log_Call{Call: _e.mock.On("Log", ctx, params)}
}

func (_c *MockAuditService_Log_Call) Run(run func(ctx context.Context, params audit.LogParams)) *MockAuditService_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 audit.LogParams
		if args[1] != nil {
			arg1 = args[1].(audit.LogParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditService_Log_Call) Return(err error) *MockAuditService_Log_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditService_Log_Call) RunAndReturn(run func(ctx context.Context, params audit.LogParams) error) *MockAuditService_Log_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoleRepository creates a new instance of MockRoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleRepository {
	mock := &MockRoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoleRepository is an autogenerated mock type for the RoleRepository type
type MockRoleRepository struct {
	mock.Mock
}

type MockRoleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleRepository) EXPECT() *MockRoleRepository_Expecter {
	return &MockRoleRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) Count(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockRoleRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoleRepository_Expecter) Count(ctx any) *MockRoleRepository_Count_Call {
	return &MockRoleRepository_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockRoleRepository_Count_Call) Run(run func(ctx context.Context)) *MockRoleRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoleRepository_Count_Call) Return(n int64, err error) *MockRoleRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRoleRepository_Count_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockRoleRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) Create(ctx context.Context, params sqlc.CreateRoleParams) (sqlc.Role, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 sqlc.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateRoleParams) (sqlc.Role, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateRoleParams) sqlc.Role); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(sqlc.Role)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.CreateRoleParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.CreateRoleParams
func (_e *MockRoleRepository_Expecter) Create(ctx any, params any) *MockRoleRepository_Create_Call {
	return &MockRoleRepository_Create_Call{Call: _e.mock.On("Create", ctx, params)}
}

func (_c *MockRoleRepository_Create_Call) Run(run func(ctx context.Context, params sqlc.CreateRoleParams)) *MockRoleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CreateRoleParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CreateRoleParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleRepository_Create_Call) Return(role sqlc.Role, err error) *MockRoleRepository_Create_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *MockRoleRepository_Create_Call) RunAndReturn(run func(ctx context.Context, params sqlc.CreateRoleParams) (sqlc.Role, error)) *MockRoleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoleRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRoleRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockRoleRepository_Expecter) Delete(ctx any, id any) *MockRoleRepository_Delete_Call {
	return &MockRoleRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRoleRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockRoleRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleRepository_Delete_Call) Return(err error) *MockRoleRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoleRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockRoleRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByName provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) ExistsByName(ctx context.Context, name string) (bool, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByName")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleRepository_ExistsByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByName'
type MockRoleRepository_ExistsByName_Call struct {
	*mock.Call
}

// ExistsByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRoleRepository_Expecter) ExistsByName(ctx any, name any) *MockRoleRepository_ExistsByName_Call {
	return &MockRoleRepository_ExistsByName_Call{Call: _e.mock.On("ExistsByName", ctx, name)}
}

func (_c *MockRoleRepository_ExistsByName_Call) Run(run func(ctx context.Context, name string)) *MockRoleRepository_ExistsByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleRepository_ExistsByName_Call) Return(b bool, err error) *MockRoleRepository_ExistsByName_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRoleRepository_ExistsByName_Call) RunAndReturn(run func(ctx context.Context, name string) (bool, error)) *MockRoleRepository_ExistsByName_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) FindByID(ctx context.Context, id int64) (sqlc.Role, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 sqlc.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (sqlc.Role, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) sqlc.Role); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.Role)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRoleRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockRoleRepository_Expecter) FindByID(ctx any, id any) *MockRoleRepository_FindByID_Call {
	return &MockRoleRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRoleRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockRoleRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleRepository_FindByID_Call) Return(role sqlc.Role, err error) *MockRoleRepository_FindByID_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *MockRoleRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (sqlc.Role, error)) *MockRoleRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) FindByName(ctx context.Context, name string) (sqlc.Role, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 sqlc.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (sqlc.Role, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) sqlc.Role); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(sqlc.Role)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockRoleRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRoleRepository_Expecter) FindByName(ctx any, name any) *MockRoleRepository_FindByName_Call {
	return &MockRoleRepository_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *MockRoleRepository_FindByName_Call) Run(run func(ctx context.Context, name string)) *MockRoleRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleRepository_FindByName_Call) Return(role sqlc.Role, err error) *MockRoleRepository_FindByName_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *MockRoleRepository_FindByName_Call) RunAndReturn(run func(ctx context.Context, name string) (sqlc.Role, error)) *MockRoleRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) List(ctx context.Context, offset int32, limit int32) ([]sqlc.Role, error) {
	ret := _mock.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []sqlc.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, int32) ([]sqlc.Role, error)); ok {
		return returnFunc(ctx, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, int32) []sqlc.Role); ok {
		r0 = returnFunc(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32, int32) error); ok {
		r1 = returnFunc(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoleRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRoleRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int32
//   - limit int32
func (_e *MockRoleRepository_Expecter) List(ctx any, offset any, limit any) *MockRoleRepository_List_Call {
	return &MockRoleRepository_List_Call{Call: _e.mock.On("List", ctx, offset, limit)}
}

func (_c *MockRoleRepository_List_Call) Run(run func(ctx context.Context, offset int32, limit int32)) *MockRoleRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRoleRepository_List_Call) Return(roles []sqlc.Role, err error) *MockRoleRepository_List_Call {
	_c.Call.Return(roles, err)
	return _c
}

func (_c *MockRoleRepository_List_Call) RunAndReturn(run func(ctx context.Context, offset int32, limit int32) ([]sqlc.Role, error)) *MockRoleRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRoleRepository
func (_mock *MockRoleRepository) Update(ctx context.Context, params sqlc.UpdateRoleParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateRoleParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoleRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRoleRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.UpdateRoleParams
func (_e *MockRoleRepository_Expecter) Update(ctx any, params any) *MockRoleRepository_Update_Call {
	return &MockRoleRepository_Update_Call{Call: _e.mock.On("Update", ctx, params)}
}

func (_c *MockRoleRepository_Update_Call) Run(run func(ctx context.Context, params sqlc.UpdateRoleParams)) *MockRoleRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateRoleParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateRoleParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleRepository_Update_Call) Return(err error) *MockRoleRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoleRepository_Update_Call) RunAndReturn(run func(ctx context.Context, params sqlc.UpdateRoleParams) error) *MockRoleRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStaffUserRepository creates a new instance of MockStaffUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStaffUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStaffUserRepository {
	mock := &MockStaffUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStaffUserRepository is an autogenerated mock type for the StaffUserRepository type
type MockStaffUserRepository struct {
	mock.Mock
}

type MockStaffUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStaffUserRepository) EXPECT() *MockStaffUserRepository_Expecter {
	return &MockStaffUserRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockStaffUserRepository
func (_mock *MockStaffUserRepository) Count(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStaffUserRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockStaffUserRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStaffUserRepository_Expecter) Count(ctx any) *MockStaffUserRepository_Count_Call {
	return &MockStaffUserRepository_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockStaffUserRepository_Count_Call) Run(run func(ctx context.Context)) *MockStaffUserRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStaffUserRepository_Count_Call) Return(n int64, err error) *MockStaffUserRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStaffUserRepository_Count_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockStaffUserRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockStaffUserRepository
func (_mock *MockStaffUserRepository) Create(ctx context.Context, params sqlc.CreateStaffUserParams) (sqlc.StaffUser, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 sqlc.StaffUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateStaffUserParams) (sqlc.StaffUser, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateStaffUserParams) sqlc.StaffUser); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(sqlc.StaffUser)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.CreateStaffUserParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStaffUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStaffUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.CreateStaffUserParams
func (_e *MockStaffUserRepository_Expecter) Create(ctx any, params any) *MockStaffUserRepository_Create_Call {
	return &MockStaffUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, params)}
}

func (_c *MockStaffUserRepository_Create_Call) Run(run func(ctx context.Context, params sqlc.CreateStaffUserParams)) *MockStaffUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CreateStaffUserParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CreateStaffUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStaffUserRepository_Create_Call) Return(staffUser sqlc.StaffUser, err error) *MockStaffUserRepository_Create_Call {
	_c.Call.Return(staffUser, err)
	return _c
}

func (_c *MockStaffUserRepository_Create_Call) RunAndReturn(run func(ctx context.Context, params sqlc.CreateStaffUserParams) (sqlc.StaffUser, error)) *MockStaffUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockStaffUserRepository
func (_mock *MockStaffUserRepository) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStaffUserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStaffUserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockStaffUserRepository_Expecter) Delete(ctx any, id any) *MockStaffUserRepository_Delete_Call {
	return &MockStaffUserRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockStaffUserRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockStaffUserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStaffUserRepository_Delete_Call) Return(err error) *MockStaffUserRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStaffUserRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockStaffUserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByEmail provides a mock function for the type MockStaffUserRepository
func (_mock *MockStaffUserRepository) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByEmail")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStaffUserRepository_ExistsByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByEmail'
type MockStaffUserRepository_ExistsByEmail_Call struct {
	*mock.Call
}

// ExistsByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockStaffUserRepository_Expecter) ExistsByEmail(ctx any, email any) *MockStaffUserRepository_ExistsByEmail_Call {
	return &MockStaffUserRepository_ExistsByEmail_Call{Call: _e.mock.On("ExistsByEmail", ctx, email)}
}

func (_c *MockStaffUserRepository_ExistsByEmail_Call) Run(run func(ctx context.Context, email string)) *MockStaffUserRepository_ExistsByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStaffUserRepository_ExistsByEmail_Call) Return(b bool, err error) *MockStaffUserRepository_ExistsByEmail_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockStaffUserRepository_ExistsByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (bool, error)) *MockStaffUserRepository_ExistsByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockStaffUserRepository
func (_mock *MockStaffUserRepository) FindByEmail(ctx context.Context, email string) (sqlc.StaffUser, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 sqlc.StaffUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (sqlc.StaffUser, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) sqlc.StaffUser); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(sqlc.StaffUser)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStaffUserRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockStaffUserRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockStaffUserRepository_Expecter) FindByEmail(ctx any, email any) *MockStaffUserRepository_FindByEmail_Call {
	return &MockStaffUserRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *MockStaffUserRepository_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *MockStaffUserRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStaffUserRepository_FindByEmail_Call) Return(staffUser sqlc.StaffUser, err error) *MockStaffUserRepository_FindByEmail_Call {
	_c.Call.Return(staffUser, err)
	return _c
}

func (_c *MockStaffUserRepository_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (sqlc.StaffUser, error)) *MockStaffUserRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockStaffUserRepository
func (_mock *MockStaffUserRepository) FindByID(ctx context.Context, id int64) (sqlc.StaffUser, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 sqlc.StaffUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (sqlc.StaffUser, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) sqlc.StaffUser); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.StaffUser)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStaffUserRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockStaffUserRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockStaffUserRepository_Expecter) FindByID(ctx any, id any) *MockStaffUserRepository_FindByID_Call {
	return &MockStaffUserRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockStaffUserRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockStaffUserRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStaffUserRepository_FindByID_Call) Return(staffUser sqlc.StaffUser, err error) *MockStaffUserRepository_FindByID_Call {
	_c.Call.Return(staffUser, err)
	return _c
}

func (_c *MockStaffUserRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (sqlc.StaffUser, error)) *MockStaffUserRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockStaffUserRepository
func (_mock *MockStaffUserRepository) List(ctx context.Context, offset int32, limit int32) ([]sqlc.ListStaffUsersRow, error) {
	ret := _mock.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []sqlc.ListStaffUsersRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, int32) ([]sqlc.ListStaffUsersRow, error)); ok {
		return returnFunc(ctx, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, int32) []sqlc.ListStaffUsersRow); ok {
		r0 = returnFunc(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.ListStaffUsersRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32, int32) error); ok {
		r1 = returnFunc(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStaffUserRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockStaffUserRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int32
//   - limit int32
func (_e *MockStaffUserRepository_Expecter) List(ctx any, offset any, limit any) *MockStaffUserRepository_List_Call {
	return &MockStaffUserRepository_List_Call{Call: _e.mock.On("List", ctx, offset, limit)}
}

func (_c *MockStaffUserRepository_List_Call) Run(run func(ctx context.Context, offset int32, limit int32)) *MockStaffUserRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStaffUserRepository_List_Call) Return(listStaffUsersRows []sqlc.ListStaffUsersRow, err error) *MockStaffUserRepository_List_Call {
	_c.Call.Return(listStaffUsersRows, err)
	return _c
}

func (_c *MockStaffUserRepository_List_Call) RunAndReturn(run func(ctx context.Context, offset int32, limit int32) ([]sqlc.ListStaffUsersRow, error)) *MockStaffUserRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockStaffUserRepository
func (_mock *MockStaffUserRepository) Search(ctx context.Context, keyword string, offset int32, limit int32) ([]sqlc.SearchStaffUsersRow, error) {
	ret := _mock.Called(ctx, keyword, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []sqlc.SearchStaffUsersRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int32, int32) ([]sqlc.SearchStaffUsersRow, error)); ok {
		return returnFunc(ctx, keyword, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int32, int32) []sqlc.SearchStaffUsersRow); ok {
		r0 = returnFunc(ctx, keyword, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.SearchStaffUsersRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int32, int32) error); ok {
		r1 = returnFunc(ctx, keyword, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStaffUserRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockStaffUserRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - keyword string
//   - offset int32
//   - limit int32
func (_e *MockStaffUserRepository_Expecter) Search(ctx any, keyword any, offset any, limit any) *MockStaffUserRepository_Search_Call {
	return &MockStaffUserRepository_Search_Call{Call: _e.mock.On("Search", ctx, keyword, offset, limit)}
}

func (_c *MockStaffUserRepository_Search_Call) Run(run func(ctx context.Context, keyword string, offset int32, limit int32)) *MockStaffUserRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		var arg3 int32
		if args[3] != nil {
			arg3 = args[3].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStaffUserRepository_Search_Call) Return(searchStaffUsersRows []sqlc.SearchStaffUsersRow, err error) *MockStaffUserRepository_Search_Call {
	_c.Call.Return(searchStaffUsersRows, err)
	return _c
}

func (_c *MockStaffUserRepository_Search_Call) RunAndReturn(run func(ctx context.Context, keyword string, offset int32, limit int32) ([]sqlc.SearchStaffUsersRow, error)) *MockStaffUserRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockStaffUserRepository
func (_mock *MockStaffUserRepository) Update(ctx context.Context, params sqlc.UpdateStaffUserParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateStaffUserParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStaffUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockStaffUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.UpdateStaffUserParams
func (_e *MockStaffUserRepository_Expecter) Update(ctx any, params any) *MockStaffUserRepository_Update_Call {
	return &MockStaffUserRepository_Update_Call{Call: _e.mock.On("Update", ctx, params)}
}

func (_c *MockStaffUserRepository_Update_Call) Run(run func(ctx context.Context, params sqlc.UpdateStaffUserParams)) *MockStaffUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateStaffUserParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateStaffUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStaffUserRepository_Update_Call) Return(err error) *MockStaffUserRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStaffUserRepository_Update_Call) RunAndReturn(run func(ctx context.Context, params sqlc.UpdateStaffUserParams) error) *MockStaffUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function for the type MockStaffUserRepository
func (_mock *MockStaffUserRepository) UpdatePassword(ctx context.Context, params sqlc.UpdateStaffPasswordParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateStaffPasswordParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStaffUserRepository_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type MockStaffUserRepository_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.UpdateStaffPasswordParams
func (_e *MockStaffUserRepository_Expecter) UpdatePassword(ctx any, params any) *MockStaffUserRepository_UpdatePassword_Call {
	return &MockStaffUserRepository_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, params)}
}

func (_c *MockStaffUserRepository_UpdatePassword_Call) Run(run func(ctx context.Context, params sqlc.UpdateStaffPasswordParams)) *MockStaffUserRepository_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateStaffPasswordParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateStaffPasswordParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStaffUserRepository_UpdatePassword_Call) Return(err error) *MockStaffUserRepository_UpdatePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStaffUserRepository_UpdatePassword_Call) RunAndReturn(run func(ctx context.Context, params sqlc.UpdateStaffPasswordParams) error) *MockStaffUserRepository_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockStaffUserRepository
func (_mock *MockStaffUserRepository) UpdateStatus(ctx context.Context, params sqlc.UpdateStaffStatusParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateStaffStatusParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStaffUserRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockStaffUserRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - params sqlc.UpdateStaffStatusParams
func (_e *MockStaffUserRepository_Expecter) UpdateStatus(ctx any, params any) *MockStaffUserRepository_UpdateStatus_Call {
	return &MockStaffUserRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, params)}
}

func (_c *MockStaffUserRepository_UpdateStatus_Call) Run(run func(ctx context.Context, params sqlc.UpdateStaffStatusParams)) *MockStaffUserRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateStaffStatusParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateStaffStatusParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStaffUserRepository_UpdateStatus_Call) Return(err error) *MockStaffUserRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStaffUserRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, params sqlc.UpdateStaffStatusParams) error) *MockStaffUserRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
