package audit

const (
	ACTION_STAFF_CREATE          = "STAFF_CREATE"
	ACTION_STAFF_UPDATE          = "STAFF_UPDATE"
	ACTION_STAFF_UPDATE_STATUS   = "STAFF_UPDATE_STATUS"
	ACTION_STAFF_UPDATE_PASSWORD = "STAFF_UPDATE_PASSWORD"
)

const (
	ENTITY_TYPE_STAFF        = "staff_user"
	ENTITY_TYPE_SEGMENT      = "segment"
	ENTITY_TYPE_NOTIFICATION = "notification"
)
