// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one

SELECT COUNT(*)
FROM audit_logs
`

// ==========================================
// COUNT
// ==========================================
func (q *Queries) CountAuditLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one

INSERT INTO audit_logs (
    actor_user_id,
    action,
    entity_type,
    entity_id,
    before_json,
    after_json,
    ip_address
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING
    id,
    actor_user_id,
    action,
    entity_type,
    entity_id,
    before_json,
    after_json,
    ip_address,
    created_at
`

type CreateAuditLogParams struct {
	ActorUserID int64       `db:"actor_user_id"`
	Action      string      `db:"action"`
	EntityType  string      `db:"entity_type"`
	EntityID    pgtype.Int8 `db:"entity_id"`
	BeforeJson  []byte      `db:"before_json"`
	AfterJson   []byte      `db:"after_json"`
	IpAddress   pgtype.Text `db:"ip_address"`
}

type CreateAuditLogRow struct {
	ID          int64              `db:"id"`
	ActorUserID int64              `db:"actor_user_id"`
	Action      string             `db:"action"`
	EntityType  string             `db:"entity_type"`
	EntityID    pgtype.Int8        `db:"entity_id"`
	BeforeJson  []byte             `db:"before_json"`
	AfterJson   []byte             `db:"after_json"`
	IpAddress   pgtype.Text        `db:"ip_address"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
}

// ==========================================
// CREATE
// ==========================================
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (CreateAuditLogRow, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.BeforeJson,
		arg.AfterJson,
		arg.IpAddress,
	)
	var i CreateAuditLogRow
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.BeforeJson,
		&i.AfterJson,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditLogByID = `-- name: GetAuditLogByID :one

SELECT
    id,
    actor_user_id,
    action,
    entity_type,
    entity_id,
    before_json,
    after_json,
    ip_address,
    created_at
FROM audit_logs
WHERE id = $1
LIMIT 1
`

type GetAuditLogByIDRow struct {
	ID          int64              `db:"id"`
	ActorUserID int64              `db:"actor_user_id"`
	Action      string             `db:"action"`
	EntityType  string             `db:"entity_type"`
	EntityID    pgtype.Int8        `db:"entity_id"`
	BeforeJson  []byte             `db:"before_json"`
	AfterJson   []byte             `db:"after_json"`
	IpAddress   pgtype.Text        `db:"ip_address"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
}

// ==========================================
// GET
// ==========================================
func (q *Queries) GetAuditLogByID(ctx context.Context, id int64) (GetAuditLogByIDRow, error) {
	row := q.db.QueryRow(ctx, getAuditLogByID, id)
	var i GetAuditLogByIDRow
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.BeforeJson,
		&i.AfterJson,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many

SELECT
    al.id,
    su.name AS actor_name,
    al.action,
    al.entity_type,
    al.entity_id,
    al.ip_address,
    al.created_at
FROM audit_logs al
JOIN staff_users su
    ON su.id = al.actor_user_id
ORDER BY al.created_at DESC
LIMIT $2
OFFSET $1
`

type ListAuditLogsParams struct {
	Offset int32 `db:"offset"`
	Limit  int32 `db:"limit"`
}

type ListAuditLogsRow struct {
	ID         int64              `db:"id"`
	ActorName  string             `db:"actor_name"`
	Action     string             `db:"action"`
	EntityType string             `db:"entity_type"`
	EntityID   pgtype.Int8        `db:"entity_id"`
	IpAddress  pgtype.Text        `db:"ip_address"`
	CreatedAt  pgtype.Timestamptz `db:"created_at"`
}

// ==========================================
// LIST
// ==========================================
func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorName,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
