// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    actor_user_id,
    action,
    entity_type,
    entity_name,
    entity_id,
    before_json,
    after_json,
    ip_address,
    user_agent
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, actor_user_id, action, entity_type, entity_name, entity_id, before_json, after_json, ip_address, user_agent, created_at
`

type CreateAuditLogParams struct {
	ActorUserID int64       `db:"actor_user_id"`
	Action      string      `db:"action"`
	EntityType  string      `db:"entity_type"`
	EntityName  pgtype.Text `db:"entity_name"`
	EntityID    pgtype.Int8 `db:"entity_id"`
	BeforeJson  []byte      `db:"before_json"`
	AfterJson   []byte      `db:"after_json"`
	IpAddress   pgtype.Text `db:"ip_address"`
	UserAgent   pgtype.Text `db:"user_agent"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityName,
		arg.EntityID,
		arg.BeforeJson,
		arg.AfterJson,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.EntityType,
		&i.EntityName,
		&i.EntityID,
		&i.BeforeJson,
		&i.AfterJson,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditLogByID = `-- name: GetAuditLogByID :one
SELECT
    id,
    actor_user_id,
    action,
    entity_type,
    entity_name,
    entity_id,
    before_json,
    after_json,
    ip_address,
    user_agent,
    created_at
FROM audit_logs
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAuditLogByID(ctx context.Context, id int64) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditLogByID, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.EntityType,
		&i.EntityName,
		&i.EntityID,
		&i.BeforeJson,
		&i.AfterJson,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditLogsByActor = `-- name: GetAuditLogsByActor :many
SELECT
    id,
    actor_user_id,
    action,
    entity_type,
    entity_name,
    entity_id,
    before_json,
    after_json,
    ip_address,
    user_agent,
    created_at
FROM audit_logs
WHERE actor_user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAuditLogsByActor(ctx context.Context, actorUserID int64) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogsByActor, actorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.EntityType,
			&i.EntityName,
			&i.EntityID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditLogsByEntity = `-- name: GetAuditLogsByEntity :many
SELECT
    id,
    actor_user_id,
    action,
    entity_type,
    entity_name,
    entity_id,
    before_json,
    after_json,
    ip_address,
    user_agent,
    created_at
FROM audit_logs
WHERE entity_type = $1 AND entity_id = $2
ORDER BY created_at DESC
`

type GetAuditLogsByEntityParams struct {
	EntityType string      `db:"entity_type"`
	EntityID   pgtype.Int8 `db:"entity_id"`
}

func (q *Queries) GetAuditLogsByEntity(ctx context.Context, arg GetAuditLogsByEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogsByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.EntityType,
			&i.EntityName,
			&i.EntityID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT
    id,
    actor_user_id,
    action,
    entity_type,
    entity_name,
    entity_id,
    before_json,
    after_json,
    ip_address,
    user_agent,
    created_at
FROM audit_logs
WHERE
    ($1::bigint IS NULL OR actor_user_id = $1) AND
    ($2::text IS NULL OR entity_type = $2) AND
    ($3::timestamptz IS NULL OR created_at >= $3) AND
    ($4::timestamptz IS NULL OR created_at <= $4)
ORDER BY created_at DESC
`

type ListAuditLogsParams struct {
	Column1 int64              `db:"column_1"`
	Column2 string             `db:"column_2"`
	Column3 pgtype.Timestamptz `db:"column_3"`
	Column4 pgtype.Timestamptz `db:"column_4"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.EntityType,
			&i.EntityName,
			&i.EntityID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
