// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeviceToken = `-- name: CreateDeviceToken :one
INSERT INTO device_tokens (
    user_id,
    provider,
    platform,
    installation_id,
    push_token,
    app_version,
    os_version,
    device_model,
    is_active,
    last_seen_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, user_id, provider, platform, installation_id, push_token, app_version, os_version, device_model, is_active, last_seen_at, created_at, updated_at
`

type CreateDeviceTokenParams struct {
	UserID         int64              `db:"user_id"`
	Provider       string             `db:"provider"`
	Platform       string             `db:"platform"`
	InstallationID pgtype.Text        `db:"installation_id"`
	PushToken      string             `db:"push_token"`
	AppVersion     pgtype.Text        `db:"app_version"`
	OsVersion      pgtype.Text        `db:"os_version"`
	DeviceModel    pgtype.Text        `db:"device_model"`
	IsActive       bool               `db:"is_active"`
	LastSeenAt     pgtype.Timestamptz `db:"last_seen_at"`
}

func (q *Queries) CreateDeviceToken(ctx context.Context, arg CreateDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, createDeviceToken,
		arg.UserID,
		arg.Provider,
		arg.Platform,
		arg.InstallationID,
		arg.PushToken,
		arg.AppVersion,
		arg.OsVersion,
		arg.DeviceModel,
		arg.IsActive,
		arg.LastSeenAt,
	)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Platform,
		&i.InstallationID,
		&i.PushToken,
		&i.AppVersion,
		&i.OsVersion,
		&i.DeviceModel,
		&i.IsActive,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM device_tokens
WHERE id = $1
`

func (q *Queries) DeleteDeviceToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, id)
	return err
}

const deleteDeviceTokensByUser = `-- name: DeleteDeviceTokensByUser :exec
DELETE FROM device_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteDeviceTokensByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteDeviceTokensByUser, userID)
	return err
}

const getDeviceTokenByID = `-- name: GetDeviceTokenByID :one
SELECT
    id,
    user_id,
    provider,
    platform,
    installation_id,
    push_token,
    app_version,
    os_version,
    device_model,
    is_active,
    last_seen_at,
    created_at,
    updated_at
FROM device_tokens
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDeviceTokenByID(ctx context.Context, id int64) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, getDeviceTokenByID, id)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Platform,
		&i.InstallationID,
		&i.PushToken,
		&i.AppVersion,
		&i.OsVersion,
		&i.DeviceModel,
		&i.IsActive,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceTokenByPushToken = `-- name: GetDeviceTokenByPushToken :one
SELECT
    id,
    user_id,
    provider,
    platform,
    installation_id,
    push_token,
    app_version,
    os_version,
    device_model,
    is_active,
    last_seen_at,
    created_at,
    updated_at
FROM device_tokens
WHERE push_token = $1
LIMIT 1
`

func (q *Queries) GetDeviceTokenByPushToken(ctx context.Context, pushToken string) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, getDeviceTokenByPushToken, pushToken)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Platform,
		&i.InstallationID,
		&i.PushToken,
		&i.AppVersion,
		&i.OsVersion,
		&i.DeviceModel,
		&i.IsActive,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceTokensByUserID = `-- name: GetDeviceTokensByUserID :many
SELECT
    id,
    user_id,
    provider,
    platform,
    installation_id,
    push_token,
    app_version,
    os_version,
    device_model,
    is_active,
    last_seen_at,
    created_at,
    updated_at
FROM device_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetDeviceTokensByUserID(ctx context.Context, userID int64) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, getDeviceTokensByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceToken{}
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.Platform,
			&i.InstallationID,
			&i.PushToken,
			&i.AppVersion,
			&i.OsVersion,
			&i.DeviceModel,
			&i.IsActive,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceTokens = `-- name: ListDeviceTokens :many
SELECT
    id,
    user_id,
    provider,
    platform,
    installation_id,
    push_token,
    app_version,
    os_version,
    device_model,
    is_active,
    last_seen_at,
    created_at,
    updated_at
FROM device_tokens
WHERE
    ($1::bigint IS NULL OR user_id = $1) AND
    ($2::boolean IS NULL OR is_active = $2)
ORDER BY id
`

type ListDeviceTokensParams struct {
	Column1 int64 `db:"column_1"`
	Column2 bool  `db:"column_2"`
}

func (q *Queries) ListDeviceTokens(ctx context.Context, arg ListDeviceTokensParams) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, listDeviceTokens, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceToken{}
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.Platform,
			&i.InstallationID,
			&i.PushToken,
			&i.AppVersion,
			&i.OsVersion,
			&i.DeviceModel,
			&i.IsActive,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceToken = `-- name: UpdateDeviceToken :exec
UPDATE device_tokens
SET
    provider = $2,
    platform = $3,
    installation_id = $4,
    push_token = $5,
    app_version = $6,
    os_version = $7,
    device_model = $8,
    is_active = $9,
    last_seen_at = $10,
    updated_at = NOW()
WHERE id = $1
`

type UpdateDeviceTokenParams struct {
	ID             int64              `db:"id"`
	Provider       string             `db:"provider"`
	Platform       string             `db:"platform"`
	InstallationID pgtype.Text        `db:"installation_id"`
	PushToken      string             `db:"push_token"`
	AppVersion     pgtype.Text        `db:"app_version"`
	OsVersion      pgtype.Text        `db:"os_version"`
	DeviceModel    pgtype.Text        `db:"device_model"`
	IsActive       bool               `db:"is_active"`
	LastSeenAt     pgtype.Timestamptz `db:"last_seen_at"`
}

func (q *Queries) UpdateDeviceToken(ctx context.Context, arg UpdateDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, updateDeviceToken,
		arg.ID,
		arg.Provider,
		arg.Platform,
		arg.InstallationID,
		arg.PushToken,
		arg.AppVersion,
		arg.OsVersion,
		arg.DeviceModel,
		arg.IsActive,
		arg.LastSeenAt,
	)
	return err
}

const updateDeviceTokenActive = `-- name: UpdateDeviceTokenActive :exec
UPDATE device_tokens
SET
    is_active = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateDeviceTokenActiveParams struct {
	ID       int64 `db:"id"`
	IsActive bool  `db:"is_active"`
}

func (q *Queries) UpdateDeviceTokenActive(ctx context.Context, arg UpdateDeviceTokenActiveParams) error {
	_, err := q.db.Exec(ctx, updateDeviceTokenActive, arg.ID, arg.IsActive)
	return err
}

const updateDeviceTokenLastSeen = `-- name: UpdateDeviceTokenLastSeen :exec
UPDATE device_tokens
SET
    last_seen_at = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateDeviceTokenLastSeenParams struct {
	ID         int64              `db:"id"`
	LastSeenAt pgtype.Timestamptz `db:"last_seen_at"`
}

func (q *Queries) UpdateDeviceTokenLastSeen(ctx context.Context, arg UpdateDeviceTokenLastSeenParams) error {
	_, err := q.db.Exec(ctx, updateDeviceTokenLastSeen, arg.ID, arg.LastSeenAt)
	return err
}
