// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDeviceTokensByUser = `-- name: CountDeviceTokensByUser :one

SELECT COUNT(*)
FROM device_tokens
WHERE user_id = $1
`

// ==========================================
// COUNT
// ==========================================
func (q *Queries) CountDeviceTokensByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countDeviceTokensByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeviceToken = `-- name: CreateDeviceToken :one

INSERT INTO device_tokens (
    user_id,
    platform,
    installation_id,
    push_token
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING
    id,
    user_id,
    platform,
    installation_id,
    push_token,
    is_active,
    last_seen_at,
    created_at,
    updated_at
`

type CreateDeviceTokenParams struct {
	UserID         int64       `db:"user_id"`
	Platform       string      `db:"platform"`
	InstallationID pgtype.Text `db:"installation_id"`
	PushToken      string      `db:"push_token"`
}

type CreateDeviceTokenRow struct {
	ID             int64              `db:"id"`
	UserID         int64              `db:"user_id"`
	Platform       string             `db:"platform"`
	InstallationID pgtype.Text        `db:"installation_id"`
	PushToken      string             `db:"push_token"`
	IsActive       bool               `db:"is_active"`
	LastSeenAt     pgtype.Timestamptz `db:"last_seen_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at"`
}

// ==========================================
// CREATE
// ==========================================
func (q *Queries) CreateDeviceToken(ctx context.Context, arg CreateDeviceTokenParams) (CreateDeviceTokenRow, error) {
	row := q.db.QueryRow(ctx, createDeviceToken,
		arg.UserID,
		arg.Platform,
		arg.InstallationID,
		arg.PushToken,
	)
	var i CreateDeviceTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.InstallationID,
		&i.PushToken,
		&i.IsActive,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec

DELETE
FROM device_tokens
WHERE id = $1
`

// ==========================================
// DELETE
// ==========================================
func (q *Queries) DeleteDeviceToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, id)
	return err
}

const existsDeviceToken = `-- name: ExistsDeviceToken :one

SELECT EXISTS (
    SELECT 1
    FROM device_tokens
    WHERE push_token = $1
)
`

// ==========================================
// EXISTS
// ==========================================
func (q *Queries) ExistsDeviceToken(ctx context.Context, pushToken string) (bool, error) {
	row := q.db.QueryRow(ctx, existsDeviceToken, pushToken)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getDeviceTokenByID = `-- name: GetDeviceTokenByID :one

SELECT
    id,
    user_id,
    platform,
    installation_id,
    push_token,
    is_active,
    last_seen_at,
    created_at,
    updated_at
FROM device_tokens
WHERE id = $1
LIMIT 1
`

type GetDeviceTokenByIDRow struct {
	ID             int64              `db:"id"`
	UserID         int64              `db:"user_id"`
	Platform       string             `db:"platform"`
	InstallationID pgtype.Text        `db:"installation_id"`
	PushToken      string             `db:"push_token"`
	IsActive       bool               `db:"is_active"`
	LastSeenAt     pgtype.Timestamptz `db:"last_seen_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at"`
}

// ==========================================
// GET
// ==========================================
func (q *Queries) GetDeviceTokenByID(ctx context.Context, id int64) (GetDeviceTokenByIDRow, error) {
	row := q.db.QueryRow(ctx, getDeviceTokenByID, id)
	var i GetDeviceTokenByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.InstallationID,
		&i.PushToken,
		&i.IsActive,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceTokenByPushToken = `-- name: GetDeviceTokenByPushToken :one
SELECT
    id,
    user_id,
    platform,
    installation_id,
    push_token,
    is_active,
    last_seen_at,
    created_at,
    updated_at
FROM device_tokens
WHERE push_token = $1
LIMIT 1
`

type GetDeviceTokenByPushTokenRow struct {
	ID             int64              `db:"id"`
	UserID         int64              `db:"user_id"`
	Platform       string             `db:"platform"`
	InstallationID pgtype.Text        `db:"installation_id"`
	PushToken      string             `db:"push_token"`
	IsActive       bool               `db:"is_active"`
	LastSeenAt     pgtype.Timestamptz `db:"last_seen_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at"`
}

func (q *Queries) GetDeviceTokenByPushToken(ctx context.Context, pushToken string) (GetDeviceTokenByPushTokenRow, error) {
	row := q.db.QueryRow(ctx, getDeviceTokenByPushToken, pushToken)
	var i GetDeviceTokenByPushTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.InstallationID,
		&i.PushToken,
		&i.IsActive,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeviceTokensByUser = `-- name: ListDeviceTokensByUser :many

SELECT
    id,
    user_id,
    platform,
    installation_id,
    push_token,
    is_active,
    last_seen_at,
    created_at,
    updated_at
FROM device_tokens
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $3
OFFSET $2
`

type ListDeviceTokensByUserParams struct {
	UserID int64 `db:"user_id"`
	Offset int32 `db:"offset"`
	Limit  int32 `db:"limit"`
}

type ListDeviceTokensByUserRow struct {
	ID             int64              `db:"id"`
	UserID         int64              `db:"user_id"`
	Platform       string             `db:"platform"`
	InstallationID pgtype.Text        `db:"installation_id"`
	PushToken      string             `db:"push_token"`
	IsActive       bool               `db:"is_active"`
	LastSeenAt     pgtype.Timestamptz `db:"last_seen_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at"`
}

// ==========================================
// LIST
// ==========================================
func (q *Queries) ListDeviceTokensByUser(ctx context.Context, arg ListDeviceTokensByUserParams) ([]ListDeviceTokensByUserRow, error) {
	rows, err := q.db.Query(ctx, listDeviceTokensByUser, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeviceTokensByUserRow{}
	for rows.Next() {
		var i ListDeviceTokensByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.InstallationID,
			&i.PushToken,
			&i.IsActive,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceToken = `-- name: UpdateDeviceToken :exec

UPDATE device_tokens
SET
    push_token = $1,
    last_seen_at = NOW(),
    updated_at = NOW()
WHERE id = $2
`

type UpdateDeviceTokenParams struct {
	PushToken string `db:"push_token"`
	ID        int64  `db:"id"`
}

// ==========================================
// UPDATE
// ==========================================
func (q *Queries) UpdateDeviceToken(ctx context.Context, arg UpdateDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, updateDeviceToken, arg.PushToken, arg.ID)
	return err
}

const updateDeviceTokenStatus = `-- name: UpdateDeviceTokenStatus :exec
UPDATE device_tokens
SET
    is_active = $1,
    updated_at = NOW()
WHERE id = $2
`

type UpdateDeviceTokenStatusParams struct {
	IsActive bool  `db:"is_active"`
	ID       int64 `db:"id"`
}

func (q *Queries) UpdateDeviceTokenStatus(ctx context.Context, arg UpdateDeviceTokenStatusParams) error {
	_, err := q.db.Exec(ctx, updateDeviceTokenStatus, arg.IsActive, arg.ID)
	return err
}
