// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDeviceTokensByUser = `-- name: CountDeviceTokensByUser :one

SELECT COUNT(*)
FROM device_tokens
WHERE user_id = $1
`

// ==========================================
// COUNT
// ==========================================
func (q *Queries) CountDeviceTokensByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countDeviceTokensByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeviceToken = `-- name: CreateDeviceToken :one

INSERT INTO device_tokens (
    user_id,
    platform,
    installation_id,
    push_token,
    provider,
    app_version,
    os_version,
    device_model
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING
    id,
    user_id,
    platform,
    installation_id,
    push_token,
    provider,
    app_version,
    os_version,
    device_model,
    is_active,
    last_seen_at,
    created_at,
    updated_at
`

type CreateDeviceTokenParams struct {
	UserID         int64       `db:"user_id"`
	Platform       string      `db:"platform"`
	InstallationID pgtype.Text `db:"installation_id"`
	PushToken      string      `db:"push_token"`
	Provider       string      `db:"provider"`
	AppVersion     pgtype.Text `db:"app_version"`
	OsVersion      pgtype.Text `db:"os_version"`
	DeviceModel    pgtype.Text `db:"device_model"`
}

type CreateDeviceTokenRow struct {
	ID             int64              `db:"id"`
	UserID         int64              `db:"user_id"`
	Platform       string             `db:"platform"`
	InstallationID pgtype.Text        `db:"installation_id"`
	PushToken      string             `db:"push_token"`
	Provider       string             `db:"provider"`
	AppVersion     pgtype.Text        `db:"app_version"`
	OsVersion      pgtype.Text        `db:"os_version"`
	DeviceModel    pgtype.Text        `db:"device_model"`
	IsActive       bool               `db:"is_active"`
	LastSeenAt     pgtype.Timestamptz `db:"last_seen_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at"`
}

// ==========================================
// CREATE
// ==========================================
func (q *Queries) CreateDeviceToken(ctx context.Context, arg CreateDeviceTokenParams) (CreateDeviceTokenRow, error) {
	row := q.db.QueryRow(ctx, createDeviceToken,
		arg.UserID,
		arg.Platform,
		arg.InstallationID,
		arg.PushToken,
		arg.Provider,
		arg.AppVersion,
		arg.OsVersion,
		arg.DeviceModel,
	)
	var i CreateDeviceTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.InstallationID,
		&i.PushToken,
		&i.Provider,
		&i.AppVersion,
		&i.OsVersion,
		&i.DeviceModel,
		&i.IsActive,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec

DELETE
FROM device_tokens
WHERE id = $1
`

// ==========================================
// DELETE
// ==========================================
func (q *Queries) DeleteDeviceToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, id)
	return err
}

const existsDeviceToken = `-- name: ExistsDeviceToken :one

SELECT EXISTS (
    SELECT 1
    FROM device_tokens
    WHERE push_token = $1
)
`

// ==========================================
// EXISTS
// ==========================================
func (q *Queries) ExistsDeviceToken(ctx context.Context, pushToken string) (bool, error) {
	row := q.db.QueryRow(ctx, existsDeviceToken, pushToken)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getDeviceTokenByID = `-- name: GetDeviceTokenByID :one

SELECT
    id,
    user_id,
    provider,
    platform,
    installation_id,
    push_token,
    app_version,
    os_version,
    device_model,
    is_active,
    last_seen_at,
    created_at,
    updated_at
FROM device_tokens
WHERE id = $1
LIMIT 1
`

// ==========================================
// GET
// ==========================================
func (q *Queries) GetDeviceTokenByID(ctx context.Context, id int64) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, getDeviceTokenByID, id)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Platform,
		&i.InstallationID,
		&i.PushToken,
		&i.AppVersion,
		&i.OsVersion,
		&i.DeviceModel,
		&i.IsActive,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceTokenByPushToken = `-- name: GetDeviceTokenByPushToken :one
SELECT
    id,
    user_id,
    provider,
    platform,
    installation_id,
    push_token,
    app_version,
    os_version,
    device_model,
    is_active,
    last_seen_at,
    created_at,
    updated_at
FROM device_tokens
WHERE push_token = $1
LIMIT 1
`

func (q *Queries) GetDeviceTokenByPushToken(ctx context.Context, pushToken string) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, getDeviceTokenByPushToken, pushToken)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Platform,
		&i.InstallationID,
		&i.PushToken,
		&i.AppVersion,
		&i.OsVersion,
		&i.DeviceModel,
		&i.IsActive,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeviceTokensByUser = `-- name: ListDeviceTokensByUser :many

SELECT
    id,
    user_id,
    provider,
    platform,
    installation_id,
    push_token,
    app_version,
    os_version,
    device_model,
    is_active,
    last_seen_at,
    created_at,
    updated_at
FROM device_tokens
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $3
OFFSET $2
`

type ListDeviceTokensByUserParams struct {
	UserID int64 `db:"user_id"`
	Offset int32 `db:"offset"`
	Limit  int32 `db:"limit"`
}

// ==========================================
// LIST
// ==========================================
func (q *Queries) ListDeviceTokensByUser(ctx context.Context, arg ListDeviceTokensByUserParams) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, listDeviceTokensByUser, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceToken{}
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.Platform,
			&i.InstallationID,
			&i.PushToken,
			&i.AppVersion,
			&i.OsVersion,
			&i.DeviceModel,
			&i.IsActive,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceToken = `-- name: UpdateDeviceToken :exec

UPDATE device_tokens
SET
    push_token = $1,
    last_seen_at = NOW(),
    updated_at = NOW()
WHERE id = $2
`

type UpdateDeviceTokenParams struct {
	PushToken string `db:"push_token"`
	ID        int64  `db:"id"`
}

// ==========================================
// UPDATE
// ==========================================
func (q *Queries) UpdateDeviceToken(ctx context.Context, arg UpdateDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, updateDeviceToken, arg.PushToken, arg.ID)
	return err
}

const updateDeviceTokenFull = `-- name: UpdateDeviceTokenFull :exec
UPDATE device_tokens
SET
    platform = $1,
    installation_id = $2,
    push_token = $3,
    provider = $4,
    app_version = $5,
    os_version = $6,
    device_model = $7,
    last_seen_at = NOW(),
    updated_at = NOW()
WHERE id = $8
`

type UpdateDeviceTokenFullParams struct {
	Platform       string      `db:"platform"`
	InstallationID pgtype.Text `db:"installation_id"`
	PushToken      string      `db:"push_token"`
	Provider       string      `db:"provider"`
	AppVersion     pgtype.Text `db:"app_version"`
	OsVersion      pgtype.Text `db:"os_version"`
	DeviceModel    pgtype.Text `db:"device_model"`
	ID             int64       `db:"id"`
}

func (q *Queries) UpdateDeviceTokenFull(ctx context.Context, arg UpdateDeviceTokenFullParams) error {
	_, err := q.db.Exec(ctx, updateDeviceTokenFull,
		arg.Platform,
		arg.InstallationID,
		arg.PushToken,
		arg.Provider,
		arg.AppVersion,
		arg.OsVersion,
		arg.DeviceModel,
		arg.ID,
	)
	return err
}

const updateDeviceTokenStatus = `-- name: UpdateDeviceTokenStatus :exec
UPDATE device_tokens
SET
    is_active = $1,
    updated_at = NOW()
WHERE id = $2
`

type UpdateDeviceTokenStatusParams struct {
	IsActive bool  `db:"is_active"`
	ID       int64 `db:"id"`
}

func (q *Queries) UpdateDeviceTokenStatus(ctx context.Context, arg UpdateDeviceTokenStatusParams) error {
	_, err := q.db.Exec(ctx, updateDeviceTokenStatus, arg.IsActive, arg.ID)
	return err
}
