// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID          int64              `db:"id"`
	ActorUserID int64              `db:"actor_user_id"`
	Action      string             `db:"action"`
	EntityType  string             `db:"entity_type"`
	EntityName  pgtype.Text        `db:"entity_name"`
	EntityID    pgtype.Int8        `db:"entity_id"`
	BeforeJson  []byte             `db:"before_json"`
	AfterJson   []byte             `db:"after_json"`
	IpAddress   pgtype.Text        `db:"ip_address"`
	UserAgent   pgtype.Text        `db:"user_agent"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
}

type DeviceToken struct {
	ID             int64              `db:"id"`
	UserID         int64              `db:"user_id"`
	Provider       string             `db:"provider"`
	Platform       string             `db:"platform"`
	InstallationID pgtype.Text        `db:"installation_id"`
	PushToken      string             `db:"push_token"`
	AppVersion     pgtype.Text        `db:"app_version"`
	OsVersion      pgtype.Text        `db:"os_version"`
	DeviceModel    pgtype.Text        `db:"device_model"`
	IsActive       bool               `db:"is_active"`
	LastSeenAt     pgtype.Timestamptz `db:"last_seen_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at"`
}

type Notification struct {
	ID           int64              `db:"id"`
	TemplateID   pgtype.Int8        `db:"template_id"`
	TemplateName pgtype.Text        `db:"template_name"`
	Title        string             `db:"title"`
	Body         string             `db:"body"`
	Payload      []byte             `db:"payload"`
	Priority     string             `db:"priority"`
	Status       string             `db:"status"`
	ScheduledAt  pgtype.Timestamptz `db:"scheduled_at"`
	PublishedAt  pgtype.Timestamptz `db:"published_at"`
	CompletedAt  pgtype.Timestamptz `db:"completed_at"`
	CreatedBy    int64              `db:"created_by"`
	CreatedAt    pgtype.Timestamptz `db:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at"`
}

type NotificationDelivery struct {
	ID                int64              `db:"id"`
	NotificationID    int64              `db:"notification_id"`
	UserID            int64              `db:"user_id"`
	DeviceTokenID     int64              `db:"device_token_id"`
	Provider          string             `db:"provider"`
	ProviderMessageID pgtype.Text        `db:"provider_message_id"`
	Status            string             `db:"status"`
	RetryCount        int32              `db:"retry_count"`
	FailedReason      pgtype.Text        `db:"failed_reason"`
	SentAt            pgtype.Timestamptz `db:"sent_at"`
	DeliveredAt       pgtype.Timestamptz `db:"delivered_at"`
	OpenedAt          pgtype.Timestamptz `db:"opened_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at"`
}

type NotificationRead struct {
	ID             int64              `db:"id"`
	NotificationID int64              `db:"notification_id"`
	UserID         int64              `db:"user_id"`
	ReadAt         pgtype.Timestamptz `db:"read_at"`
}

type NotificationTarget struct {
	ID             int64              `db:"id"`
	NotificationID int64              `db:"notification_id"`
	TargetType     string             `db:"target_type"`
	SegmentID      pgtype.Int8        `db:"segment_id"`
	UserID         pgtype.Int8        `db:"user_id"`
	UploadBatchID  pgtype.Int8        `db:"upload_batch_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at"`
}

type Role struct {
	ID          int64              `db:"id"`
	Name        string             `db:"name"`
	Description pgtype.Text        `db:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
}

type Segment struct {
	ID          int64              `db:"id"`
	Name        string             `db:"name"`
	Description pgtype.Text        `db:"description"`
	CreatedBy   int64              `db:"created_by"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
}

type SegmentMember struct {
	ID        int64              `db:"id"`
	SegmentID int64              `db:"segment_id"`
	UserID    int64              `db:"user_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
}

type StaffUser struct {
	ID           int64              `db:"id"`
	RoleID       int64              `db:"role_id"`
	Name         string             `db:"name"`
	Email        string             `db:"email"`
	PasswordHash string             `db:"password_hash"`
	IsActive     bool               `db:"is_active"`
	CreatedAt    pgtype.Timestamptz `db:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at"`
}

type Template struct {
	ID            int64              `db:"id"`
	Name          string             `db:"name"`
	TitleTemplate string             `db:"title_template"`
	BodyTemplate  string             `db:"body_template"`
	Variables     []byte             `db:"variables"`
	CreatedBy     int64              `db:"created_by"`
	IsActive      bool               `db:"is_active"`
	CreatedAt     pgtype.Timestamptz `db:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at"`
}

type UploadBatch struct {
	ID               int64              `db:"id"`
	UploadedBy       int64              `db:"uploaded_by"`
	OriginalFilename string             `db:"original_filename"`
	TotalRows        int32              `db:"total_rows"`
	ValidRows        int32              `db:"valid_rows"`
	InvalidRows      int32              `db:"invalid_rows"`
	CreatedAt        pgtype.Timestamptz `db:"created_at"`
}

type UploadBatchRow struct {
	ID           int64              `db:"id"`
	BatchID      int64              `db:"batch_id"`
	ExternalID   string             `db:"external_id"`
	IsValid      bool               `db:"is_valid"`
	ErrorMessage pgtype.Text        `db:"error_message"`
	CreatedAt    pgtype.Timestamptz `db:"created_at"`
}

type User struct {
	ID         int64              `db:"id"`
	ExternalID string             `db:"external_id"`
	Name       pgtype.Text        `db:"name"`
	Email      pgtype.Text        `db:"email"`
	Status     string             `db:"status"`
	CreatedAt  pgtype.Timestamptz `db:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at"`
}
