// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_reads.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotificationReads = `-- name: CountNotificationReads :one

SELECT COUNT(*)
FROM notification_reads
WHERE notification_id = $1
`

// ==========================================
// COUNT
// ==========================================
func (q *Queries) CountNotificationReads(ctx context.Context, notificationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationReads, notificationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotificationRead = `-- name: CreateNotificationRead :one

INSERT INTO notification_reads (
    notification_id,
    user_id,
    read_at
)
VALUES (
    $1,
    $2,
    NOW()
)
RETURNING
    id,
    notification_id,
    user_id,
    read_at
`

type CreateNotificationReadParams struct {
	NotificationID int64 `db:"notification_id"`
	UserID         int64 `db:"user_id"`
}

// ==========================================
// CREATE
// ==========================================
func (q *Queries) CreateNotificationRead(ctx context.Context, arg CreateNotificationReadParams) (NotificationRead, error) {
	row := q.db.QueryRow(ctx, createNotificationRead, arg.NotificationID, arg.UserID)
	var i NotificationRead
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.UserID,
		&i.ReadAt,
	)
	return i, err
}

const existsNotificationRead = `-- name: ExistsNotificationRead :one

SELECT EXISTS (
    SELECT 1
    FROM notification_reads
    WHERE
        notification_id = $1
        AND user_id = $2
)
`

type ExistsNotificationReadParams struct {
	NotificationID int64 `db:"notification_id"`
	UserID         int64 `db:"user_id"`
}

// ==========================================
// EXISTS
// ==========================================
func (q *Queries) ExistsNotificationRead(ctx context.Context, arg ExistsNotificationReadParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsNotificationRead, arg.NotificationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listNotificationReads = `-- name: ListNotificationReads :many

SELECT
    nr.id,
    u.name,
    u.email,
    nr.read_at
FROM notification_reads nr
JOIN users u
    ON u.id = nr.user_id
WHERE nr.notification_id = $1
ORDER BY nr.read_at DESC
LIMIT $3
OFFSET $2
`

type ListNotificationReadsParams struct {
	NotificationID int64 `db:"notification_id"`
	Offset         int32 `db:"offset"`
	Limit          int32 `db:"limit"`
}

type ListNotificationReadsRow struct {
	ID     int64              `db:"id"`
	Name   pgtype.Text        `db:"name"`
	Email  pgtype.Text        `db:"email"`
	ReadAt pgtype.Timestamptz `db:"read_at"`
}

// ==========================================
// LIST
// ==========================================
func (q *Queries) ListNotificationReads(ctx context.Context, arg ListNotificationReadsParams) ([]ListNotificationReadsRow, error) {
	rows, err := q.db.Query(ctx, listNotificationReads, arg.NotificationID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationReadsRow{}
	for rows.Next() {
		var i ListNotificationReadsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
