// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotifications = `-- name: CountNotifications :one

SELECT COUNT(*)
FROM notifications
`

// ==========================================
// COUNT
// ==========================================
func (q *Queries) CountNotifications(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNotifications)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNotificationsWithFilters = `-- name: CountNotificationsWithFilters :one
SELECT COUNT(DISTINCT n.id)
FROM notifications n
LEFT JOIN notification_targets nt ON nt.notification_id = n.id
WHERE 
    ($1::text = '' OR n.status = $1)
    AND ($2::text = '' OR nt.target_type = $2)
    AND ($3::text = '' OR n.title ILIKE '%' || $3 || '%')
`

type CountNotificationsWithFiltersParams struct {
	Status     string `db:"status"`
	TargetType string `db:"target_type"`
	Keyword    string `db:"keyword"`
}

func (q *Queries) CountNotificationsWithFilters(ctx context.Context, arg CountNotificationsWithFiltersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationsWithFilters, arg.Status, arg.TargetType, arg.Keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one

INSERT INTO notifications (
    title,
    body,
    template_id,
    status,
    created_by,
    scheduled_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING
    id,
    title,
    body,
    template_id,
    status,
    created_by,
    scheduled_at,
    created_at,
    updated_at
`

type CreateNotificationParams struct {
	Title       string             `db:"title"`
	Body        string             `db:"body"`
	TemplateID  pgtype.Int8        `db:"template_id"`
	Status      string             `db:"status"`
	CreatedBy   int64              `db:"created_by"`
	ScheduledAt pgtype.Timestamptz `db:"scheduled_at"`
}

type CreateNotificationRow struct {
	ID          int64              `db:"id"`
	Title       string             `db:"title"`
	Body        string             `db:"body"`
	TemplateID  pgtype.Int8        `db:"template_id"`
	Status      string             `db:"status"`
	CreatedBy   int64              `db:"created_by"`
	ScheduledAt pgtype.Timestamptz `db:"scheduled_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
}

// ==========================================
// CREATE
// ==========================================
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (CreateNotificationRow, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.Title,
		arg.Body,
		arg.TemplateID,
		arg.Status,
		arg.CreatedBy,
		arg.ScheduledAt,
	)
	var i CreateNotificationRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.TemplateID,
		&i.Status,
		&i.CreatedBy,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec

DELETE
FROM notifications
WHERE id = $1
`

// ==========================================
// DELETE
// ==========================================
func (q *Queries) DeleteNotification(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteNotification, id)
	return err
}

const getNotificationByID = `-- name: GetNotificationByID :one

SELECT
    id,
    title,
    body,
    template_id,
    template_name,
    payload,
    priority,
    status,
    created_by,
    scheduled_at,
    published_at,
    completed_at,
    created_at,
    updated_at
FROM notifications
WHERE id = $1
LIMIT 1
`

type GetNotificationByIDRow struct {
	ID           int64              `db:"id"`
	Title        string             `db:"title"`
	Body         string             `db:"body"`
	TemplateID   pgtype.Int8        `db:"template_id"`
	TemplateName pgtype.Text        `db:"template_name"`
	Payload      []byte             `db:"payload"`
	Priority     string             `db:"priority"`
	Status       string             `db:"status"`
	CreatedBy    int64              `db:"created_by"`
	ScheduledAt  pgtype.Timestamptz `db:"scheduled_at"`
	PublishedAt  pgtype.Timestamptz `db:"published_at"`
	CompletedAt  pgtype.Timestamptz `db:"completed_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at"`
}

// ==========================================
// GET
// ==========================================
func (q *Queries) GetNotificationByID(ctx context.Context, id int64) (GetNotificationByIDRow, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i GetNotificationByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.TemplateID,
		&i.TemplateName,
		&i.Payload,
		&i.Priority,
		&i.Status,
		&i.CreatedBy,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationStatistics = `-- name: GetNotificationStatistics :one
SELECT
    COUNT(DISTINCT nt.user_id) AS targeted,
    COUNT(CASE WHEN nd.status = 'DELIVERED' OR nd.status = 'OPENED' THEN 1 END) AS delivered,
    COUNT(CASE WHEN nd.status = 'OPENED' THEN 1 END) AS opened
FROM notification_targets nt
LEFT JOIN notification_deliveries nd ON nd.notification_id = nt.notification_id AND nd.user_id = nt.user_id
WHERE nt.notification_id = $1
`

type GetNotificationStatisticsRow struct {
	Targeted  int64 `db:"targeted"`
	Delivered int64 `db:"delivered"`
	Opened    int64 `db:"opened"`
}

func (q *Queries) GetNotificationStatistics(ctx context.Context, notificationID int64) (GetNotificationStatisticsRow, error) {
	row := q.db.QueryRow(ctx, getNotificationStatistics, notificationID)
	var i GetNotificationStatisticsRow
	err := row.Scan(&i.Targeted, &i.Delivered, &i.Opened)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many

SELECT
    n.id,
    n.title,
    n.status,
    su.name AS created_by_name,
    n.scheduled_at,
    n.created_at
FROM notifications n
JOIN staff_users su
    ON su.id = n.created_by
ORDER BY n.created_at DESC
LIMIT $2
OFFSET $1
`

type ListNotificationsParams struct {
	Offset int32 `db:"offset"`
	Limit  int32 `db:"limit"`
}

type ListNotificationsRow struct {
	ID            int64              `db:"id"`
	Title         string             `db:"title"`
	Status        string             `db:"status"`
	CreatedByName string             `db:"created_by_name"`
	ScheduledAt   pgtype.Timestamptz `db:"scheduled_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at"`
}

// ==========================================
// LIST
// ==========================================
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsRow{}
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.CreatedByName,
			&i.ScheduledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsWithFilters = `-- name: ListNotificationsWithFilters :many
SELECT
    n.id,
    n.title,
    n.status,
    su.name AS created_by_name,
    n.scheduled_at,
    n.created_at,
    COALESCE(
        (SELECT DISTINCT nt.target_type 
         FROM notification_targets nt 
         WHERE nt.notification_id = n.id 
         LIMIT 1), 
        'BROADCAST'
    )::text AS target_type
FROM notifications n
JOIN staff_users su ON su.id = n.created_by
WHERE 
    ($1::text = '' OR n.status = $1)
    AND ($2::text = '' OR COALESCE(
        (SELECT DISTINCT nt.target_type 
         FROM notification_targets nt 
         WHERE nt.notification_id = n.id 
         LIMIT 1), 
        'BROADCAST'
    ) = $2)
    AND ($3::text = '' OR n.title ILIKE '%' || $3 || '%')
ORDER BY n.created_at DESC
LIMIT $5 OFFSET $4
`

type ListNotificationsWithFiltersParams struct {
	Status     string `db:"status"`
	TargetType string `db:"target_type"`
	Keyword    string `db:"keyword"`
	Offset     int32  `db:"offset"`
	Limit      int32  `db:"limit"`
}

type ListNotificationsWithFiltersRow struct {
	ID            int64              `db:"id"`
	Title         string             `db:"title"`
	Status        string             `db:"status"`
	CreatedByName string             `db:"created_by_name"`
	ScheduledAt   pgtype.Timestamptz `db:"scheduled_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at"`
	TargetType    string             `db:"target_type"`
}

func (q *Queries) ListNotificationsWithFilters(ctx context.Context, arg ListNotificationsWithFiltersParams) ([]ListNotificationsWithFiltersRow, error) {
	rows, err := q.db.Query(ctx, listNotificationsWithFilters,
		arg.Status,
		arg.TargetType,
		arg.Keyword,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsWithFiltersRow{}
	for rows.Next() {
		var i ListNotificationsWithFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.CreatedByName,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.TargetType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledNotificationsDue = `-- name: ListScheduledNotificationsDue :many
SELECT
    id,
    title,
    body,
    template_id,
    status,
    created_by,
    scheduled_at,
    created_at,
    updated_at
FROM notifications
WHERE status = 'SCHEDULED'
  AND scheduled_at <= NOW()
ORDER BY scheduled_at ASC
LIMIT $1
`

type ListScheduledNotificationsDueRow struct {
	ID          int64              `db:"id"`
	Title       string             `db:"title"`
	Body        string             `db:"body"`
	TemplateID  pgtype.Int8        `db:"template_id"`
	Status      string             `db:"status"`
	CreatedBy   int64              `db:"created_by"`
	ScheduledAt pgtype.Timestamptz `db:"scheduled_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
}

func (q *Queries) ListScheduledNotificationsDue(ctx context.Context, limit int32) ([]ListScheduledNotificationsDueRow, error) {
	rows, err := q.db.Query(ctx, listScheduledNotificationsDue, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduledNotificationsDueRow{}
	for rows.Next() {
		var i ListScheduledNotificationsDueRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.TemplateID,
			&i.Status,
			&i.CreatedBy,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationSent = `-- name: MarkNotificationSent :exec
UPDATE notifications
SET
    status = 'SENT',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkNotificationSent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markNotificationSent, id)
	return err
}

const searchNotifications = `-- name: SearchNotifications :many

SELECT
    n.id,
    n.title,
    n.status,
    su.name AS created_by_name,
    n.scheduled_at,
    n.created_at
FROM notifications n
JOIN staff_users su
    ON su.id = n.created_by
WHERE
    n.title ILIKE '%' || $1 || '%'
ORDER BY n.created_at DESC
LIMIT $3
OFFSET $2
`

type SearchNotificationsParams struct {
	Keyword pgtype.Text `db:"keyword"`
	Offset  int32       `db:"offset"`
	Limit   int32       `db:"limit"`
}

type SearchNotificationsRow struct {
	ID            int64              `db:"id"`
	Title         string             `db:"title"`
	Status        string             `db:"status"`
	CreatedByName string             `db:"created_by_name"`
	ScheduledAt   pgtype.Timestamptz `db:"scheduled_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at"`
}

// ==========================================
// SEARCH
// ==========================================
func (q *Queries) SearchNotifications(ctx context.Context, arg SearchNotificationsParams) ([]SearchNotificationsRow, error) {
	rows, err := q.db.Query(ctx, searchNotifications, arg.Keyword, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchNotificationsRow{}
	for rows.Next() {
		var i SearchNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.CreatedByName,
			&i.ScheduledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotification = `-- name: UpdateNotification :exec

UPDATE notifications
SET
    title = $1,
    body = $2,
    template_id = $3,
    scheduled_at = $4,
    updated_at = NOW()
WHERE id = $5
`

type UpdateNotificationParams struct {
	Title       string             `db:"title"`
	Body        string             `db:"body"`
	TemplateID  pgtype.Int8        `db:"template_id"`
	ScheduledAt pgtype.Timestamptz `db:"scheduled_at"`
	ID          int64              `db:"id"`
}

// ==========================================
// UPDATE
// ==========================================
func (q *Queries) UpdateNotification(ctx context.Context, arg UpdateNotificationParams) error {
	_, err := q.db.Exec(ctx, updateNotification,
		arg.Title,
		arg.Body,
		arg.TemplateID,
		arg.ScheduledAt,
		arg.ID,
	)
	return err
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :exec
UPDATE notifications
SET
    status = $1,
    updated_at = NOW()
WHERE id = $2
`

type UpdateNotificationStatusParams struct {
	Status string `db:"status"`
	ID     int64  `db:"id"`
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error {
	_, err := q.db.Exec(ctx, updateNotificationStatus, arg.Status, arg.ID)
	return err
}

const updateNotificationStatusIfScheduled = `-- name: UpdateNotificationStatusIfScheduled :execrows
UPDATE notifications
SET
    status = $1,
    updated_at = NOW()
WHERE id = $2
  AND status = 'SCHEDULED'
`

type UpdateNotificationStatusIfScheduledParams struct {
	Status string `db:"status"`
	ID     int64  `db:"id"`
}

func (q *Queries) UpdateNotificationStatusIfScheduled(ctx context.Context, arg UpdateNotificationStatusIfScheduledParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateNotificationStatusIfScheduled, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
