// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_deliveries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDelivery = `-- name: CreateDelivery :one
INSERT INTO notification_deliveries (
    notification_id,
    user_id,
    device_token_id,
    provider,
    provider_message_id,
    status,
    retry_count,
    failed_reason,
    sent_at,
    delivered_at,
    opened_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, notification_id, user_id, device_token_id, provider, provider_message_id, status, retry_count, failed_reason, sent_at, delivered_at, opened_at, created_at, updated_at
`

type CreateDeliveryParams struct {
	NotificationID    int64              `db:"notification_id"`
	UserID            int64              `db:"user_id"`
	DeviceTokenID     int64              `db:"device_token_id"`
	Provider          string             `db:"provider"`
	ProviderMessageID pgtype.Text        `db:"provider_message_id"`
	Status            string             `db:"status"`
	RetryCount        int32              `db:"retry_count"`
	FailedReason      pgtype.Text        `db:"failed_reason"`
	SentAt            pgtype.Timestamptz `db:"sent_at"`
	DeliveredAt       pgtype.Timestamptz `db:"delivered_at"`
	OpenedAt          pgtype.Timestamptz `db:"opened_at"`
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, createDelivery,
		arg.NotificationID,
		arg.UserID,
		arg.DeviceTokenID,
		arg.Provider,
		arg.ProviderMessageID,
		arg.Status,
		arg.RetryCount,
		arg.FailedReason,
		arg.SentAt,
		arg.DeliveredAt,
		arg.OpenedAt,
	)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.UserID,
		&i.DeviceTokenID,
		&i.Provider,
		&i.ProviderMessageID,
		&i.Status,
		&i.RetryCount,
		&i.FailedReason,
		&i.SentAt,
		&i.DeliveredAt,
		&i.OpenedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDelivery = `-- name: DeleteDelivery :exec
DELETE FROM notification_deliveries
WHERE id = $1
`

func (q *Queries) DeleteDelivery(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDelivery, id)
	return err
}

const getDeliveriesByNotificationID = `-- name: GetDeliveriesByNotificationID :many
SELECT
    id,
    notification_id,
    user_id,
    device_token_id,
    provider,
    provider_message_id,
    status,
    retry_count,
    failed_reason,
    sent_at,
    delivered_at,
    opened_at,
    created_at,
    updated_at
FROM notification_deliveries
WHERE notification_id = $1
ORDER BY id
`

func (q *Queries) GetDeliveriesByNotificationID(ctx context.Context, notificationID int64) ([]NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, getDeliveriesByNotificationID, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.UserID,
			&i.DeviceTokenID,
			&i.Provider,
			&i.ProviderMessageID,
			&i.Status,
			&i.RetryCount,
			&i.FailedReason,
			&i.SentAt,
			&i.DeliveredAt,
			&i.OpenedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeliveriesByStatus = `-- name: GetDeliveriesByStatus :many
SELECT
    id,
    notification_id,
    user_id,
    device_token_id,
    provider,
    provider_message_id,
    status,
    retry_count,
    failed_reason,
    sent_at,
    delivered_at,
    opened_at,
    created_at,
    updated_at
FROM notification_deliveries
WHERE status = $1
ORDER BY created_at
`

func (q *Queries) GetDeliveriesByStatus(ctx context.Context, status string) ([]NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, getDeliveriesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.UserID,
			&i.DeviceTokenID,
			&i.Provider,
			&i.ProviderMessageID,
			&i.Status,
			&i.RetryCount,
			&i.FailedReason,
			&i.SentAt,
			&i.DeliveredAt,
			&i.OpenedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeliveriesByUserID = `-- name: GetDeliveriesByUserID :many
SELECT
    id,
    notification_id,
    user_id,
    device_token_id,
    provider,
    provider_message_id,
    status,
    retry_count,
    failed_reason,
    sent_at,
    delivered_at,
    opened_at,
    created_at,
    updated_at
FROM notification_deliveries
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetDeliveriesByUserID(ctx context.Context, userID int64) ([]NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, getDeliveriesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.UserID,
			&i.DeviceTokenID,
			&i.Provider,
			&i.ProviderMessageID,
			&i.Status,
			&i.RetryCount,
			&i.FailedReason,
			&i.SentAt,
			&i.DeliveredAt,
			&i.OpenedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeliveryByID = `-- name: GetDeliveryByID :one
SELECT
    id,
    notification_id,
    user_id,
    device_token_id,
    provider,
    provider_message_id,
    status,
    retry_count,
    failed_reason,
    sent_at,
    delivered_at,
    opened_at,
    created_at,
    updated_at
FROM notification_deliveries
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDeliveryByID(ctx context.Context, id int64) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, getDeliveryByID, id)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.UserID,
		&i.DeviceTokenID,
		&i.Provider,
		&i.ProviderMessageID,
		&i.Status,
		&i.RetryCount,
		&i.FailedReason,
		&i.SentAt,
		&i.DeliveredAt,
		&i.OpenedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeliveries = `-- name: ListDeliveries :many
SELECT
    id,
    notification_id,
    user_id,
    device_token_id,
    provider,
    provider_message_id,
    status,
    retry_count,
    failed_reason,
    sent_at,
    delivered_at,
    opened_at,
    created_at,
    updated_at
FROM notification_deliveries
WHERE
    ($1::bigint IS NULL OR notification_id = $1) AND
    ($2::bigint IS NULL OR user_id = $2) AND
    ($3::text[] IS NULL OR status = ANY($3))
ORDER BY created_at DESC
`

type ListDeliveriesParams struct {
	Column1 int64    `db:"column_1"`
	Column2 int64    `db:"column_2"`
	Column3 []string `db:"column_3"`
}

func (q *Queries) ListDeliveries(ctx context.Context, arg ListDeliveriesParams) ([]NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, listDeliveries, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.UserID,
			&i.DeviceTokenID,
			&i.Provider,
			&i.ProviderMessageID,
			&i.Status,
			&i.RetryCount,
			&i.FailedReason,
			&i.SentAt,
			&i.DeliveredAt,
			&i.OpenedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDelivery = `-- name: UpdateDelivery :exec
UPDATE notification_deliveries
SET
    provider_message_id = $2,
    status = $3,
    retry_count = $4,
    failed_reason = $5,
    sent_at = $6,
    delivered_at = $7,
    opened_at = $8,
    updated_at = NOW()
WHERE id = $1
`

type UpdateDeliveryParams struct {
	ID                int64              `db:"id"`
	ProviderMessageID pgtype.Text        `db:"provider_message_id"`
	Status            string             `db:"status"`
	RetryCount        int32              `db:"retry_count"`
	FailedReason      pgtype.Text        `db:"failed_reason"`
	SentAt            pgtype.Timestamptz `db:"sent_at"`
	DeliveredAt       pgtype.Timestamptz `db:"delivered_at"`
	OpenedAt          pgtype.Timestamptz `db:"opened_at"`
}

func (q *Queries) UpdateDelivery(ctx context.Context, arg UpdateDeliveryParams) error {
	_, err := q.db.Exec(ctx, updateDelivery,
		arg.ID,
		arg.ProviderMessageID,
		arg.Status,
		arg.RetryCount,
		arg.FailedReason,
		arg.SentAt,
		arg.DeliveredAt,
		arg.OpenedAt,
	)
	return err
}

const updateDeliveryStatus = `-- name: UpdateDeliveryStatus :exec
UPDATE notification_deliveries
SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateDeliveryStatusParams struct {
	ID     int64  `db:"id"`
	Status string `db:"status"`
}

func (q *Queries) UpdateDeliveryStatus(ctx context.Context, arg UpdateDeliveryStatusParams) error {
	_, err := q.db.Exec(ctx, updateDeliveryStatus, arg.ID, arg.Status)
	return err
}
