// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_deliveries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotificationDeliveries = `-- name: CountNotificationDeliveries :one

SELECT COUNT(*)
FROM notification_deliveries
WHERE notification_id = $1
`

// ==========================================
// COUNT
// ==========================================
func (q *Queries) CountNotificationDeliveries(ctx context.Context, notificationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationDeliveries, notificationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotificationDelivery = `-- name: CreateNotificationDelivery :one

INSERT INTO notification_deliveries (
    notification_id,
    user_id,
    provider,
    provider_message_id,
    status
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING
    id,
    notification_id,
    user_id,
    provider,
    provider_message_id,
    status,
    sent_at,
    delivered_at,
    opened_at,
    failed_reason,
    created_at,
    updated_at
`

type CreateNotificationDeliveryParams struct {
	NotificationID    int64       `db:"notification_id"`
	UserID            int64       `db:"user_id"`
	Provider          string      `db:"provider"`
	ProviderMessageID pgtype.Text `db:"provider_message_id"`
	Status            string      `db:"status"`
}

type CreateNotificationDeliveryRow struct {
	ID                int64              `db:"id"`
	NotificationID    int64              `db:"notification_id"`
	UserID            int64              `db:"user_id"`
	Provider          string             `db:"provider"`
	ProviderMessageID pgtype.Text        `db:"provider_message_id"`
	Status            string             `db:"status"`
	SentAt            pgtype.Timestamptz `db:"sent_at"`
	DeliveredAt       pgtype.Timestamptz `db:"delivered_at"`
	OpenedAt          pgtype.Timestamptz `db:"opened_at"`
	FailedReason      pgtype.Text        `db:"failed_reason"`
	CreatedAt         pgtype.Timestamptz `db:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at"`
}

// ==========================================
// CREATE
// ==========================================
func (q *Queries) CreateNotificationDelivery(ctx context.Context, arg CreateNotificationDeliveryParams) (CreateNotificationDeliveryRow, error) {
	row := q.db.QueryRow(ctx, createNotificationDelivery,
		arg.NotificationID,
		arg.UserID,
		arg.Provider,
		arg.ProviderMessageID,
		arg.Status,
	)
	var i CreateNotificationDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.UserID,
		&i.Provider,
		&i.ProviderMessageID,
		&i.Status,
		&i.SentAt,
		&i.DeliveredAt,
		&i.OpenedAt,
		&i.FailedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationDeliveryByID = `-- name: GetNotificationDeliveryByID :one

SELECT
    id,
    notification_id,
    user_id,
    provider,
    provider_message_id,
    status,
    sent_at,
    delivered_at,
    opened_at,
    failed_reason,
    created_at,
    updated_at
FROM notification_deliveries
WHERE id = $1
LIMIT 1
`

type GetNotificationDeliveryByIDRow struct {
	ID                int64              `db:"id"`
	NotificationID    int64              `db:"notification_id"`
	UserID            int64              `db:"user_id"`
	Provider          string             `db:"provider"`
	ProviderMessageID pgtype.Text        `db:"provider_message_id"`
	Status            string             `db:"status"`
	SentAt            pgtype.Timestamptz `db:"sent_at"`
	DeliveredAt       pgtype.Timestamptz `db:"delivered_at"`
	OpenedAt          pgtype.Timestamptz `db:"opened_at"`
	FailedReason      pgtype.Text        `db:"failed_reason"`
	CreatedAt         pgtype.Timestamptz `db:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at"`
}

// ==========================================
// GET
// ==========================================
func (q *Queries) GetNotificationDeliveryByID(ctx context.Context, id int64) (GetNotificationDeliveryByIDRow, error) {
	row := q.db.QueryRow(ctx, getNotificationDeliveryByID, id)
	var i GetNotificationDeliveryByIDRow
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.UserID,
		&i.Provider,
		&i.ProviderMessageID,
		&i.Status,
		&i.SentAt,
		&i.DeliveredAt,
		&i.OpenedAt,
		&i.FailedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotificationDeliveries = `-- name: ListNotificationDeliveries :many

SELECT
    nd.id,
    nd.provider,
    nd.status,
    u.name,
    u.email,
    nd.sent_at,
    nd.delivered_at,
    nd.opened_at
FROM notification_deliveries nd
JOIN users u
    ON u.id = nd.user_id
WHERE nd.notification_id = $1
ORDER BY nd.created_at
LIMIT $3
OFFSET $2
`

type ListNotificationDeliveriesParams struct {
	NotificationID int64 `db:"notification_id"`
	Offset         int32 `db:"offset"`
	Limit          int32 `db:"limit"`
}

type ListNotificationDeliveriesRow struct {
	ID          int64              `db:"id"`
	Provider    string             `db:"provider"`
	Status      string             `db:"status"`
	Name        pgtype.Text        `db:"name"`
	Email       pgtype.Text        `db:"email"`
	SentAt      pgtype.Timestamptz `db:"sent_at"`
	DeliveredAt pgtype.Timestamptz `db:"delivered_at"`
	OpenedAt    pgtype.Timestamptz `db:"opened_at"`
}

// ==========================================
// LIST
// ==========================================
func (q *Queries) ListNotificationDeliveries(ctx context.Context, arg ListNotificationDeliveriesParams) ([]ListNotificationDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listNotificationDeliveries, arg.NotificationID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationDeliveriesRow{}
	for rows.Next() {
		var i ListNotificationDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Status,
			&i.Name,
			&i.Email,
			&i.SentAt,
			&i.DeliveredAt,
			&i.OpenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationDelivered = `-- name: MarkNotificationDelivered :exec

UPDATE notification_deliveries
SET
    status = 'DELIVERED',
    delivered_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

// ==========================================
// UPDATE STATUS
// ==========================================
func (q *Queries) MarkNotificationDelivered(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markNotificationDelivered, id)
	return err
}

const markNotificationFailed = `-- name: MarkNotificationFailed :exec
UPDATE notification_deliveries
SET
    status = 'FAILED',
    failed_reason = $1,
    updated_at = NOW()
WHERE id = $2
`

type MarkNotificationFailedParams struct {
	FailedReason pgtype.Text `db:"failed_reason"`
	ID           int64       `db:"id"`
}

func (q *Queries) MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationFailed, arg.FailedReason, arg.ID)
	return err
}

const markNotificationOpened = `-- name: MarkNotificationOpened :exec
UPDATE notification_deliveries
SET
    status = 'OPENED',
    opened_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkNotificationOpened(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markNotificationOpened, id)
	return err
}
