// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    template_id,
    template_name,
    title,
    body,
    payload,
    priority,
    status,
    scheduled_at,
    published_at,
    completed_at,
    created_by
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, template_id, template_name, title, body, payload, priority, status, scheduled_at, published_at, completed_at, created_by, created_at, updated_at
`

type CreateNotificationParams struct {
	TemplateID   pgtype.Int8        `db:"template_id"`
	TemplateName pgtype.Text        `db:"template_name"`
	Title        string             `db:"title"`
	Body         string             `db:"body"`
	Payload      []byte             `db:"payload"`
	Priority     string             `db:"priority"`
	Status       string             `db:"status"`
	ScheduledAt  pgtype.Timestamptz `db:"scheduled_at"`
	PublishedAt  pgtype.Timestamptz `db:"published_at"`
	CompletedAt  pgtype.Timestamptz `db:"completed_at"`
	CreatedBy    int64              `db:"created_by"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.TemplateID,
		arg.TemplateName,
		arg.Title,
		arg.Body,
		arg.Payload,
		arg.Priority,
		arg.Status,
		arg.ScheduledAt,
		arg.PublishedAt,
		arg.CompletedAt,
		arg.CreatedBy,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.TemplateName,
		&i.Title,
		&i.Body,
		&i.Payload,
		&i.Priority,
		&i.Status,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications
WHERE id = $1
`

func (q *Queries) DeleteNotification(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteNotification, id)
	return err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT
    id,
    template_id,
    template_name,
    title,
    body,
    payload,
    priority,
    status,
    scheduled_at,
    published_at,
    completed_at,
    created_by,
    created_at,
    updated_at
FROM notifications
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id int64) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.TemplateName,
		&i.Title,
		&i.Body,
		&i.Payload,
		&i.Priority,
		&i.Status,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationsByCreatedBy = `-- name: GetNotificationsByCreatedBy :many
SELECT
    id,
    template_id,
    template_name,
    title,
    body,
    payload,
    priority,
    status,
    scheduled_at,
    published_at,
    completed_at,
    created_by,
    created_at,
    updated_at
FROM notifications
WHERE created_by = $1
ORDER BY created_at DESC
`

func (q *Queries) GetNotificationsByCreatedBy(ctx context.Context, createdBy int64) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getNotificationsByCreatedBy, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.TemplateName,
			&i.Title,
			&i.Body,
			&i.Payload,
			&i.Priority,
			&i.Status,
			&i.ScheduledAt,
			&i.PublishedAt,
			&i.CompletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationsByStatus = `-- name: GetNotificationsByStatus :many
SELECT
    id,
    template_id,
    template_name,
    title,
    body,
    payload,
    priority,
    status,
    scheduled_at,
    published_at,
    completed_at,
    created_by,
    created_at,
    updated_at
FROM notifications
WHERE status = $1
ORDER BY created_at DESC
`

func (q *Queries) GetNotificationsByStatus(ctx context.Context, status string) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getNotificationsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.TemplateName,
			&i.Title,
			&i.Body,
			&i.Payload,
			&i.Priority,
			&i.Status,
			&i.ScheduledAt,
			&i.PublishedAt,
			&i.CompletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT
    id,
    template_id,
    template_name,
    title,
    body,
    payload,
    priority,
    status,
    scheduled_at,
    published_at,
    completed_at,
    created_by,
    created_at,
    updated_at
FROM notifications
WHERE
    ($1::text[] IS NULL OR status = ANY($1)) AND
    ($2::bigint IS NULL OR created_by = $2) AND
    ($3::timestamptz IS NULL OR created_at >= $3) AND
    ($4::timestamptz IS NULL OR created_at <= $4)
ORDER BY created_at DESC
`

type ListNotificationsParams struct {
	Column1 []string           `db:"column_1"`
	Column2 int64              `db:"column_2"`
	Column3 pgtype.Timestamptz `db:"column_3"`
	Column4 pgtype.Timestamptz `db:"column_4"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.TemplateName,
			&i.Title,
			&i.Body,
			&i.Payload,
			&i.Priority,
			&i.Status,
			&i.ScheduledAt,
			&i.PublishedAt,
			&i.CompletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotification = `-- name: UpdateNotification :exec
UPDATE notifications
SET
    template_id = $2,
    template_name = $3,
    title = $4,
    body = $5,
    payload = $6,
    priority = $7,
    status = $8,
    scheduled_at = $9,
    published_at = $10,
    completed_at = $11,
    updated_at = NOW()
WHERE id = $1
`

type UpdateNotificationParams struct {
	ID           int64              `db:"id"`
	TemplateID   pgtype.Int8        `db:"template_id"`
	TemplateName pgtype.Text        `db:"template_name"`
	Title        string             `db:"title"`
	Body         string             `db:"body"`
	Payload      []byte             `db:"payload"`
	Priority     string             `db:"priority"`
	Status       string             `db:"status"`
	ScheduledAt  pgtype.Timestamptz `db:"scheduled_at"`
	PublishedAt  pgtype.Timestamptz `db:"published_at"`
	CompletedAt  pgtype.Timestamptz `db:"completed_at"`
}

func (q *Queries) UpdateNotification(ctx context.Context, arg UpdateNotificationParams) error {
	_, err := q.db.Exec(ctx, updateNotification,
		arg.ID,
		arg.TemplateID,
		arg.TemplateName,
		arg.Title,
		arg.Body,
		arg.Payload,
		arg.Priority,
		arg.Status,
		arg.ScheduledAt,
		arg.PublishedAt,
		arg.CompletedAt,
	)
	return err
}

const updateNotificationSchedule = `-- name: UpdateNotificationSchedule :exec
UPDATE notifications
SET
    scheduled_at = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateNotificationScheduleParams struct {
	ID          int64              `db:"id"`
	ScheduledAt pgtype.Timestamptz `db:"scheduled_at"`
}

func (q *Queries) UpdateNotificationSchedule(ctx context.Context, arg UpdateNotificationScheduleParams) error {
	_, err := q.db.Exec(ctx, updateNotificationSchedule, arg.ID, arg.ScheduledAt)
	return err
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :exec
UPDATE notifications
SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateNotificationStatusParams struct {
	ID     int64  `db:"id"`
	Status string `db:"status"`
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error {
	_, err := q.db.Exec(ctx, updateNotificationStatus, arg.ID, arg.Status)
	return err
}
