// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_targets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotificationTargets = `-- name: CountNotificationTargets :one

SELECT COUNT(*)
FROM notification_targets
WHERE notification_id = $1
`

// ==========================================
// COUNT
// ==========================================
func (q *Queries) CountNotificationTargets(ctx context.Context, notificationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationTargets, notificationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotificationTarget = `-- name: CreateNotificationTarget :one

INSERT INTO notification_targets (
    notification_id,
    user_id
)
VALUES (
    $1,
    $2
)
RETURNING
    id,
    notification_id,
    user_id,
    created_at
`

type CreateNotificationTargetParams struct {
	NotificationID int64       `db:"notification_id"`
	UserID         pgtype.Int8 `db:"user_id"`
}

type CreateNotificationTargetRow struct {
	ID             int64              `db:"id"`
	NotificationID int64              `db:"notification_id"`
	UserID         pgtype.Int8        `db:"user_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at"`
}

// ==========================================
// CREATE
// ==========================================
func (q *Queries) CreateNotificationTarget(ctx context.Context, arg CreateNotificationTargetParams) (CreateNotificationTargetRow, error) {
	row := q.db.QueryRow(ctx, createNotificationTarget, arg.NotificationID, arg.UserID)
	var i CreateNotificationTargetRow
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const createNotificationTargetFull = `-- name: CreateNotificationTargetFull :one
INSERT INTO notification_targets (
    notification_id,
    target_type,
    segment_id,
    user_id,
    upload_batch_id
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING
    id,
    notification_id,
    target_type,
    segment_id,
    user_id,
    upload_batch_id,
    created_at
`

type CreateNotificationTargetFullParams struct {
	NotificationID int64       `db:"notification_id"`
	TargetType     string      `db:"target_type"`
	SegmentID      pgtype.Int8 `db:"segment_id"`
	UserID         pgtype.Int8 `db:"user_id"`
	UploadBatchID  pgtype.Int8 `db:"upload_batch_id"`
}

func (q *Queries) CreateNotificationTargetFull(ctx context.Context, arg CreateNotificationTargetFullParams) (NotificationTarget, error) {
	row := q.db.QueryRow(ctx, createNotificationTargetFull,
		arg.NotificationID,
		arg.TargetType,
		arg.SegmentID,
		arg.UserID,
		arg.UploadBatchID,
	)
	var i NotificationTarget
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.TargetType,
		&i.SegmentID,
		&i.UserID,
		&i.UploadBatchID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotificationTarget = `-- name: DeleteNotificationTarget :exec

DELETE
FROM notification_targets
WHERE id = $1
`

// ==========================================
// DELETE
// ==========================================
func (q *Queries) DeleteNotificationTarget(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteNotificationTarget, id)
	return err
}

const deleteNotificationTargetsByNotification = `-- name: DeleteNotificationTargetsByNotification :exec
DELETE FROM notification_targets WHERE notification_id = $1
`

func (q *Queries) DeleteNotificationTargetsByNotification(ctx context.Context, notificationID int64) error {
	_, err := q.db.Exec(ctx, deleteNotificationTargetsByNotification, notificationID)
	return err
}

const listNotificationTargets = `-- name: ListNotificationTargets :many

SELECT
    nt.id,
    nt.notification_id,
    nt.target_type,
    nt.segment_id,
    u.id AS user_id,
    u.external_id,
    u.name,
    u.email,
    nt.created_at
FROM notification_targets nt
LEFT JOIN users u ON u.id = nt.user_id
WHERE nt.notification_id = $1
ORDER BY u.name NULLS FIRST
LIMIT $3
OFFSET $2
`

type ListNotificationTargetsParams struct {
	NotificationID int64 `db:"notification_id"`
	Offset         int32 `db:"offset"`
	Limit          int32 `db:"limit"`
}

type ListNotificationTargetsRow struct {
	ID             int64              `db:"id"`
	NotificationID int64              `db:"notification_id"`
	TargetType     string             `db:"target_type"`
	SegmentID      pgtype.Int8        `db:"segment_id"`
	UserID         pgtype.Int8        `db:"user_id"`
	ExternalID     pgtype.Text        `db:"external_id"`
	Name           pgtype.Text        `db:"name"`
	Email          pgtype.Text        `db:"email"`
	CreatedAt      pgtype.Timestamptz `db:"created_at"`
}

// ==========================================
// LIST
// ==========================================
func (q *Queries) ListNotificationTargets(ctx context.Context, arg ListNotificationTargetsParams) ([]ListNotificationTargetsRow, error) {
	rows, err := q.db.Query(ctx, listNotificationTargets, arg.NotificationID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationTargetsRow{}
	for rows.Next() {
		var i ListNotificationTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.TargetType,
			&i.SegmentID,
			&i.UserID,
			&i.ExternalID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
