// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ==========================================
	// COUNT
	// ==========================================
	CountAuditLogs(ctx context.Context) (int64, error)
	// ==========================================
	// COUNT
	// ==========================================
	CountDeviceTokensByUser(ctx context.Context, userID int64) (int64, error)
	// ==========================================
	// COUNT
	// ==========================================
	CountNotificationDeliveries(ctx context.Context, notificationID int64) (int64, error)
	// ==========================================
	// COUNT
	// ==========================================
	CountNotificationReads(ctx context.Context, notificationID int64) (int64, error)
	// ==========================================
	// COUNT
	// ==========================================
	CountNotificationTargets(ctx context.Context, notificationID int64) (int64, error)
	// ==========================================
	// COUNT
	// ==========================================
	CountNotifications(ctx context.Context) (int64, error)
	CountNotificationsWithFilters(ctx context.Context, arg CountNotificationsWithFiltersParams) (int64, error)
	// ==========================================
	// COUNT
	// ==========================================
	CountRoles(ctx context.Context) (int64, error)
	// ==========================================
	// COUNT
	// ==========================================
	CountSegmentMembers(ctx context.Context, segmentID int64) (int64, error)
	CountSegmentMembersByUser(ctx context.Context, userID int64) (int64, error)
	// ==========================================
	// COUNT
	// ==========================================
	CountSegments(ctx context.Context) (int64, error)
	// ==========================================
	// COUNT
	// ==========================================
	CountStaffUsers(ctx context.Context) (int64, error)
	// ==========================================
	// COUNT
	// ==========================================
	CountTemplates(ctx context.Context) (int64, error)
	// ==========================================
	// COUNT
	// ==========================================
	CountUploadBatchRows(ctx context.Context, batchID int64) (int64, error)
	// ==========================================
	// COUNT
	// ==========================================
	CountUploadBatches(ctx context.Context) (int64, error)
	CountUserNotifications(ctx context.Context, userID int64) (int64, error)
	// ==========================================
	// COUNT
	// ==========================================
	CountUsers(ctx context.Context) (int64, error)
	CountUsersByStatus(ctx context.Context, status string) (int64, error)
	// ==========================================
	// CREATE
	// ==========================================
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (CreateAuditLogRow, error)
	// ==========================================
	// CREATE
	// ==========================================
	CreateDeviceToken(ctx context.Context, arg CreateDeviceTokenParams) (CreateDeviceTokenRow, error)
	// ==========================================
	// CREATE
	// ==========================================
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (CreateNotificationRow, error)
	// ==========================================
	// CREATE
	// ==========================================
	CreateNotificationDelivery(ctx context.Context, arg CreateNotificationDeliveryParams) (NotificationDelivery, error)
	// ==========================================
	// CREATE
	// ==========================================
	CreateNotificationRead(ctx context.Context, arg CreateNotificationReadParams) (NotificationRead, error)
	// ==========================================
	// CREATE
	// ==========================================
	CreateNotificationTarget(ctx context.Context, arg CreateNotificationTargetParams) (CreateNotificationTargetRow, error)
	CreateNotificationTargetFull(ctx context.Context, arg CreateNotificationTargetFullParams) (NotificationTarget, error)
	// ==========================================
	// CREATE
	// ==========================================
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	// ==========================================
	// CREATE
	// ==========================================
	CreateSegment(ctx context.Context, arg CreateSegmentParams) (Segment, error)
	// ==========================================
	// CREATE
	// ==========================================
	CreateSegmentMember(ctx context.Context, arg CreateSegmentMemberParams) (SegmentMember, error)
	// ==========================================
	// CREATE
	// ==========================================
	CreateStaffUser(ctx context.Context, arg CreateStaffUserParams) (StaffUser, error)
	// ==========================================
	// CREATE
	// ==========================================
	CreateTemplate(ctx context.Context, arg CreateTemplateParams) (CreateTemplateRow, error)
	// ==========================================
	// CREATE
	// ==========================================
	CreateUploadBatch(ctx context.Context, arg CreateUploadBatchParams) (UploadBatch, error)
	// ==========================================
	// CREATE
	// ==========================================
	CreateUploadBatchRow(ctx context.Context, arg CreateUploadBatchRowParams) (UploadBatchRow, error)
	// ==========================================
	// CREATE
	// ==========================================
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// ==========================================
	// DELETE
	// ==========================================
	DeleteDeviceToken(ctx context.Context, id int64) error
	// ==========================================
	// DELETE
	// ==========================================
	DeleteNotification(ctx context.Context, id int64) error
	// ==========================================
	// DELETE
	// ==========================================
	DeleteNotificationTarget(ctx context.Context, id int64) error
	DeleteNotificationTargetsByNotification(ctx context.Context, notificationID int64) error
	// ==========================================
	// DELETE
	// ==========================================
	DeleteRole(ctx context.Context, id int64) error
	// ==========================================
	// DELETE
	// ==========================================
	DeleteSegment(ctx context.Context, id int64) error
	// ==========================================
	// DELETE
	// ==========================================
	DeleteSegmentMember(ctx context.Context, id int64) error
	DeleteSegmentMemberBySegmentAndUser(ctx context.Context, arg DeleteSegmentMemberBySegmentAndUserParams) error
	// ==========================================
	// DELETE
	// ==========================================
	DeleteStaffUser(ctx context.Context, id int64) error
	// ==========================================
	// DELETE
	// ==========================================
	DeleteTemplate(ctx context.Context, id int64) error
	// ==========================================
	// DELETE
	// ==========================================
	DeleteUser(ctx context.Context, id int64) error
	// ==========================================
	// EXISTS
	// ==========================================
	ExistsDeviceToken(ctx context.Context, pushToken string) (bool, error)
	// ==========================================
	// EXISTS
	// ==========================================
	ExistsNotificationRead(ctx context.Context, arg ExistsNotificationReadParams) (bool, error)
	// ==========================================
	// EXISTS
	// ==========================================
	ExistsRoleByName(ctx context.Context, name string) (bool, error)
	// ==========================================
	// EXISTS
	// ==========================================
	ExistsSegmentByName(ctx context.Context, name string) (bool, error)
	// ==========================================
	// EXISTS
	// ==========================================
	ExistsStaffUserByEmail(ctx context.Context, email string) (bool, error)
	// ==========================================
	// EXISTS
	// ==========================================
	ExistsTemplateByName(ctx context.Context, name string) (bool, error)
	ExistsUserByEmail(ctx context.Context, email pgtype.Text) (bool, error)
	// ==========================================
	// EXISTS
	// ==========================================
	ExistsUserByExternalID(ctx context.Context, externalID string) (bool, error)
	// ==========================================
	// GET
	// ==========================================
	GetAuditLogByID(ctx context.Context, id int64) (GetAuditLogByIDRow, error)
	// ==========================================
	// GET
	// ==========================================
	GetDeviceTokenByID(ctx context.Context, id int64) (DeviceToken, error)
	GetDeviceTokenByPushToken(ctx context.Context, pushToken string) (DeviceToken, error)
	// ==========================================
	// GET
	// ==========================================
	GetNotificationByID(ctx context.Context, id int64) (GetNotificationByIDRow, error)
	// ==========================================
	// GET
	// ==========================================
	GetNotificationDeliveryByID(ctx context.Context, id int64) (GetNotificationDeliveryByIDRow, error)
	GetNotificationStatistics(ctx context.Context, notificationID int64) (GetNotificationStatisticsRow, error)
	// ==========================================
	// GET
	// ==========================================
	GetRoleByID(ctx context.Context, id int64) (Role, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	// ==========================================
	// GET
	// ==========================================
	GetSegmentByID(ctx context.Context, id int64) (Segment, error)
	GetSegmentByName(ctx context.Context, name string) (Segment, error)
	// ==========================================
	// GET
	// ==========================================
	GetSegmentMemberByID(ctx context.Context, id int64) (SegmentMember, error)
	GetStaffUserByEmail(ctx context.Context, email string) (StaffUser, error)
	// ==========================================
	// GET
	// ==========================================
	GetStaffUserByID(ctx context.Context, id int64) (StaffUser, error)
	// ==========================================
	// GET
	// ==========================================
	GetTemplateByID(ctx context.Context, id int64) (GetTemplateByIDRow, error)
	GetTemplateByName(ctx context.Context, name string) (GetTemplateByNameRow, error)
	// ==========================================
	// GET
	// ==========================================
	GetUploadBatchByID(ctx context.Context, id int64) (UploadBatch, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	GetUserByExternalID(ctx context.Context, externalID string) (User, error)
	// ==========================================
	// GET
	// ==========================================
	GetUserByID(ctx context.Context, id int64) (User, error)
	// ==========================================
	// LIST
	// ==========================================
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error)
	// ==========================================
	// LIST
	// ==========================================
	ListDeviceTokensByUser(ctx context.Context, arg ListDeviceTokensByUserParams) ([]DeviceToken, error)
	ListDeviceTokensByUserIDs(ctx context.Context, userIds []int64) ([]DeviceToken, error)
	// ==========================================
	// LIST
	// ==========================================
	ListNotificationDeliveries(ctx context.Context, arg ListNotificationDeliveriesParams) ([]ListNotificationDeliveriesRow, error)
	// ==========================================
	// LIST
	// ==========================================
	ListNotificationReads(ctx context.Context, arg ListNotificationReadsParams) ([]ListNotificationReadsRow, error)
	// ==========================================
	// LIST
	// ==========================================
	ListNotificationTargets(ctx context.Context, arg ListNotificationTargetsParams) ([]ListNotificationTargetsRow, error)
	// ==========================================
	// LIST
	// ==========================================
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error)
	ListNotificationsWithFilters(ctx context.Context, arg ListNotificationsWithFiltersParams) ([]ListNotificationsWithFiltersRow, error)
	// ==========================================
	// LIST
	// ==========================================
	ListRoles(ctx context.Context, arg ListRolesParams) ([]Role, error)
	// ==========================================
	// LIST
	// ==========================================
	ListSegmentMembers(ctx context.Context, arg ListSegmentMembersParams) ([]ListSegmentMembersRow, error)
	ListSegmentMembersByUser(ctx context.Context, arg ListSegmentMembersByUserParams) ([]ListSegmentMembersByUserRow, error)
	// ==========================================
	// LIST
	// ==========================================
	ListSegments(ctx context.Context, arg ListSegmentsParams) ([]ListSegmentsRow, error)
	// ==========================================
	// LIST
	// ==========================================
	ListStaffUsers(ctx context.Context, arg ListStaffUsersParams) ([]ListStaffUsersRow, error)
	// ==========================================
	// LIST
	// ==========================================
	ListTemplates(ctx context.Context, arg ListTemplatesParams) ([]ListTemplatesRow, error)
	// ==========================================
	// LIST
	// ==========================================
	ListUploadBatchRows(ctx context.Context, arg ListUploadBatchRowsParams) ([]UploadBatchRow, error)
	// ==========================================
	// LIST
	// ==========================================
	ListUploadBatches(ctx context.Context, arg ListUploadBatchesParams) ([]ListUploadBatchesRow, error)
	ListUserNotifications(ctx context.Context, arg ListUserNotificationsParams) ([]ListUserNotificationsRow, error)
	// ==========================================
	// LIST
	// ==========================================
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// ==========================================
	// FILTER
	// ==========================================
	ListUsersByStatus(ctx context.Context, arg ListUsersByStatusParams) ([]User, error)
	// ==========================================
	// UPDATE STATUS
	// ==========================================
	MarkNotificationDelivered(ctx context.Context, id int64) error
	MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) error
	MarkNotificationOpened(ctx context.Context, id int64) error
	MarkNotificationSent(ctx context.Context, id int64) error
	// ==========================================
	// SEARCH
	// ==========================================
	SearchNotifications(ctx context.Context, arg SearchNotificationsParams) ([]SearchNotificationsRow, error)
	// ==========================================
	// SEARCH
	// ==========================================
	SearchSegments(ctx context.Context, arg SearchSegmentsParams) ([]SearchSegmentsRow, error)
	// ==========================================
	// SEARCH
	// ==========================================
	SearchStaffUsers(ctx context.Context, arg SearchStaffUsersParams) ([]SearchStaffUsersRow, error)
	// ==========================================
	// SEARCH
	// ==========================================
	SearchTemplates(ctx context.Context, arg SearchTemplatesParams) ([]SearchTemplatesRow, error)
	// ==========================================
	// SEARCH
	// ==========================================
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error)
	// ==========================================
	// UPDATE
	// ==========================================
	UpdateDeviceToken(ctx context.Context, arg UpdateDeviceTokenParams) error
	UpdateDeviceTokenFull(ctx context.Context, arg UpdateDeviceTokenFullParams) error
	UpdateDeviceTokenStatus(ctx context.Context, arg UpdateDeviceTokenStatusParams) error
	// ==========================================
	// UPDATE
	// ==========================================
	UpdateNotification(ctx context.Context, arg UpdateNotificationParams) error
	UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error
	// ==========================================
	// UPDATE
	// ==========================================
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	// ==========================================
	// UPDATE
	// ==========================================
	UpdateSegment(ctx context.Context, arg UpdateSegmentParams) error
	UpdateStaffPassword(ctx context.Context, arg UpdateStaffPasswordParams) error
	UpdateStaffStatus(ctx context.Context, arg UpdateStaffStatusParams) error
	// ==========================================
	// UPDATE
	// ==========================================
	UpdateStaffUser(ctx context.Context, arg UpdateStaffUserParams) error
	// ==========================================
	// UPDATE
	// ==========================================
	UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) error
	UpdateTemplateStatus(ctx context.Context, arg UpdateTemplateStatusParams) error
	// ==========================================
	// UPDATE
	// ==========================================
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
}

var _ Querier = (*Queries)(nil)
