// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateStaffUser(ctx context.Context, arg CreateStaffUserParams) (StaffUser, error)
	DeleteRole(ctx context.Context, id int64) error
	GetRoleByID(ctx context.Context, id int64) (Role, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetStaffUserByEmail(ctx context.Context, email string) (StaffUser, error)
	GetStaffUserByID(ctx context.Context, id int64) (StaffUser, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListStaffUsers(ctx context.Context) ([]ListStaffUsersRow, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	UpdateStaffPassword(ctx context.Context, arg UpdateStaffPasswordParams) error
	UpdateStaffStatus(ctx context.Context, arg UpdateStaffStatusParams) error
}

var _ Querier = (*Queries)(nil)
