// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRoles = `-- name: CountRoles :one

SELECT COUNT(*)
FROM roles
`

// ==========================================
// COUNT
// ==========================================
func (q *Queries) CountRoles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRoles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :one

INSERT INTO roles (
    name,
    description
)
VALUES (
    $1,
    $2
)
RETURNING
    id,
    name,
    description,
    created_at,
    updated_at
`

type CreateRoleParams struct {
	Name        string      `db:"name"`
	Description pgtype.Text `db:"description"`
}

// ==========================================
// CREATE
// ==========================================
func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec

DELETE
FROM roles
WHERE id = $1
`

// ==========================================
// DELETE
// ==========================================
func (q *Queries) DeleteRole(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const existsRoleByName = `-- name: ExistsRoleByName :one

SELECT EXISTS (
    SELECT 1
    FROM roles
    WHERE name = $1
)
`

// ==========================================
// EXISTS
// ==========================================
func (q *Queries) ExistsRoleByName(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, existsRoleByName, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getRoleByID = `-- name: GetRoleByID :one

SELECT
    id,
    name,
    description,
    created_at,
    updated_at
FROM roles
WHERE id = $1
LIMIT 1
`

// ==========================================
// GET
// ==========================================
func (q *Queries) GetRoleByID(ctx context.Context, id int64) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT
    id,
    name,
    description,
    created_at,
    updated_at
FROM roles
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many

SELECT
    id,
    name,
    description,
    created_at,
    updated_at
FROM roles
ORDER BY name
LIMIT $2
OFFSET $1
`

type ListRolesParams struct {
	Offset int32 `db:"offset"`
	Limit  int32 `db:"limit"`
}

// ==========================================
// LIST
// ==========================================
func (q *Queries) ListRoles(ctx context.Context, arg ListRolesParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :exec

UPDATE roles
SET
    name = $1,
    description = $2,
    updated_at = NOW()
WHERE id = $3
`

type UpdateRoleParams struct {
	Name        string      `db:"name"`
	Description pgtype.Text `db:"description"`
	ID          int64       `db:"id"`
}

// ==========================================
// UPDATE
// ==========================================
func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.Exec(ctx, updateRole, arg.Name, arg.Description, arg.ID)
	return err
}
