// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: segment_members.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSegmentMembers = `-- name: CountSegmentMembers :one

SELECT COUNT(*)
FROM segment_members
WHERE segment_id = $1
`

// ==========================================
// COUNT
// ==========================================
func (q *Queries) CountSegmentMembers(ctx context.Context, segmentID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSegmentMembers, segmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSegmentMembersByUser = `-- name: CountSegmentMembersByUser :one
SELECT COUNT(*)
FROM segment_members
WHERE user_id = $1
`

func (q *Queries) CountSegmentMembersByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSegmentMembersByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSegmentMember = `-- name: CreateSegmentMember :one

INSERT INTO segment_members (
    segment_id,
    user_id
)
VALUES (
    $1,
    $2
)
RETURNING
    id,
    segment_id,
    user_id,
    created_at
`

type CreateSegmentMemberParams struct {
	SegmentID int64 `db:"segment_id"`
	UserID    int64 `db:"user_id"`
}

// ==========================================
// CREATE
// ==========================================
func (q *Queries) CreateSegmentMember(ctx context.Context, arg CreateSegmentMemberParams) (SegmentMember, error) {
	row := q.db.QueryRow(ctx, createSegmentMember, arg.SegmentID, arg.UserID)
	var i SegmentMember
	err := row.Scan(
		&i.ID,
		&i.SegmentID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSegmentMember = `-- name: DeleteSegmentMember :exec

DELETE
FROM segment_members
WHERE id = $1
`

// ==========================================
// DELETE
// ==========================================
func (q *Queries) DeleteSegmentMember(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSegmentMember, id)
	return err
}

const deleteSegmentMemberBySegmentAndUser = `-- name: DeleteSegmentMemberBySegmentAndUser :exec
DELETE FROM segment_members
WHERE segment_id = $1 AND user_id = $2
`

type DeleteSegmentMemberBySegmentAndUserParams struct {
	SegmentID int64 `db:"segment_id"`
	UserID    int64 `db:"user_id"`
}

func (q *Queries) DeleteSegmentMemberBySegmentAndUser(ctx context.Context, arg DeleteSegmentMemberBySegmentAndUserParams) error {
	_, err := q.db.Exec(ctx, deleteSegmentMemberBySegmentAndUser, arg.SegmentID, arg.UserID)
	return err
}

const getSegmentMemberByID = `-- name: GetSegmentMemberByID :one

SELECT
    id,
    segment_id,
    user_id,
    created_at
FROM segment_members
WHERE id = $1
LIMIT 1
`

// ==========================================
// GET
// ==========================================
func (q *Queries) GetSegmentMemberByID(ctx context.Context, id int64) (SegmentMember, error) {
	row := q.db.QueryRow(ctx, getSegmentMemberByID, id)
	var i SegmentMember
	err := row.Scan(
		&i.ID,
		&i.SegmentID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const listSegmentMembers = `-- name: ListSegmentMembers :many

SELECT
    sm.id,
    sm.segment_id,
    u.id AS user_id,
    u.name,
    u.email,
    sm.created_at
FROM segment_members sm
JOIN users u
    ON u.id = sm.user_id
WHERE sm.segment_id = $1
ORDER BY u.name
LIMIT $3
OFFSET $2
`

type ListSegmentMembersParams struct {
	SegmentID int64 `db:"segment_id"`
	Offset    int32 `db:"offset"`
	Limit     int32 `db:"limit"`
}

type ListSegmentMembersRow struct {
	ID        int64              `db:"id"`
	SegmentID int64              `db:"segment_id"`
	UserID    int64              `db:"user_id"`
	Name      pgtype.Text        `db:"name"`
	Email     pgtype.Text        `db:"email"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
}

// ==========================================
// LIST
// ==========================================
func (q *Queries) ListSegmentMembers(ctx context.Context, arg ListSegmentMembersParams) ([]ListSegmentMembersRow, error) {
	rows, err := q.db.Query(ctx, listSegmentMembers, arg.SegmentID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSegmentMembersRow{}
	for rows.Next() {
		var i ListSegmentMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.SegmentID,
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSegmentMembersByUser = `-- name: ListSegmentMembersByUser :many
SELECT
    s.id,
    s.name
FROM segments s
JOIN segment_members sm ON sm.segment_id = s.id
WHERE sm.user_id = $1
ORDER BY s.name
LIMIT $3
OFFSET $2
`

type ListSegmentMembersByUserParams struct {
	UserID int64 `db:"user_id"`
	Offset int32 `db:"offset"`
	Limit  int32 `db:"limit"`
}

type ListSegmentMembersByUserRow struct {
	ID   int64  `db:"id"`
	Name string `db:"name"`
}

func (q *Queries) ListSegmentMembersByUser(ctx context.Context, arg ListSegmentMembersByUserParams) ([]ListSegmentMembersByUserRow, error) {
	rows, err := q.db.Query(ctx, listSegmentMembersByUser, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSegmentMembersByUserRow{}
	for rows.Next() {
		var i ListSegmentMembersByUserRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
