// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: segments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSegment = `-- name: CreateSegment :one
INSERT INTO segments (
    name,
    description,
    created_by
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, description, created_by, created_at, updated_at
`

type CreateSegmentParams struct {
	Name        string      `db:"name"`
	Description pgtype.Text `db:"description"`
	CreatedBy   int64       `db:"created_by"`
}

func (q *Queries) CreateSegment(ctx context.Context, arg CreateSegmentParams) (Segment, error) {
	row := q.db.QueryRow(ctx, createSegment, arg.Name, arg.Description, arg.CreatedBy)
	var i Segment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSegment = `-- name: DeleteSegment :exec
DELETE FROM segments
WHERE id = $1
`

func (q *Queries) DeleteSegment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSegment, id)
	return err
}

const getSegmentByID = `-- name: GetSegmentByID :one
SELECT
    id,
    name,
    description,
    created_by,
    created_at,
    updated_at
FROM segments
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSegmentByID(ctx context.Context, id int64) (Segment, error) {
	row := q.db.QueryRow(ctx, getSegmentByID, id)
	var i Segment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSegmentByName = `-- name: GetSegmentByName :one
SELECT
    id,
    name,
    description,
    created_by,
    created_at,
    updated_at
FROM segments
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetSegmentByName(ctx context.Context, name string) (Segment, error) {
	row := q.db.QueryRow(ctx, getSegmentByName, name)
	var i Segment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSegments = `-- name: ListSegments :many
SELECT
    id,
    name,
    description,
    created_by,
    created_at,
    updated_at
FROM segments
ORDER BY id
`

func (q *Queries) ListSegments(ctx context.Context) ([]Segment, error) {
	rows, err := q.db.Query(ctx, listSegments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Segment{}
	for rows.Next() {
		var i Segment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSegment = `-- name: UpdateSegment :exec
UPDATE segments
SET
    name = $2,
    description = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateSegmentParams struct {
	ID          int64       `db:"id"`
	Name        string      `db:"name"`
	Description pgtype.Text `db:"description"`
}

func (q *Queries) UpdateSegment(ctx context.Context, arg UpdateSegmentParams) error {
	_, err := q.db.Exec(ctx, updateSegment, arg.ID, arg.Name, arg.Description)
	return err
}
