// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: segment_members.sql

package sqlc

import (
	"context"
)

const createSegmentMember = `-- name: CreateSegmentMember :one
INSERT INTO segment_members (
    segment_id,
    user_id
)
VALUES (
    $1,
    $2
)
RETURNING id, segment_id, user_id, created_at
`

type CreateSegmentMemberParams struct {
	SegmentID int64 `db:"segment_id"`
	UserID    int64 `db:"user_id"`
}

func (q *Queries) CreateSegmentMember(ctx context.Context, arg CreateSegmentMemberParams) (SegmentMember, error) {
	row := q.db.QueryRow(ctx, createSegmentMember, arg.SegmentID, arg.UserID)
	var i SegmentMember
	err := row.Scan(
		&i.ID,
		&i.SegmentID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSegmentMember = `-- name: DeleteSegmentMember :exec
DELETE FROM segment_members
WHERE id = $1
`

func (q *Queries) DeleteSegmentMember(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSegmentMember, id)
	return err
}

const deleteSegmentMembersBySegment = `-- name: DeleteSegmentMembersBySegment :exec
DELETE FROM segment_members
WHERE segment_id = $1
`

func (q *Queries) DeleteSegmentMembersBySegment(ctx context.Context, segmentID int64) error {
	_, err := q.db.Exec(ctx, deleteSegmentMembersBySegment, segmentID)
	return err
}

const deleteSegmentMembersByUser = `-- name: DeleteSegmentMembersByUser :exec
DELETE FROM segment_members
WHERE user_id = $1
`

func (q *Queries) DeleteSegmentMembersByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteSegmentMembersByUser, userID)
	return err
}

const getSegmentMemberByID = `-- name: GetSegmentMemberByID :one
SELECT
    id,
    segment_id,
    user_id,
    created_at
FROM segment_members
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSegmentMemberByID(ctx context.Context, id int64) (SegmentMember, error) {
	row := q.db.QueryRow(ctx, getSegmentMemberByID, id)
	var i SegmentMember
	err := row.Scan(
		&i.ID,
		&i.SegmentID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getSegmentMemberBySegmentAndUser = `-- name: GetSegmentMemberBySegmentAndUser :one
SELECT
    id,
    segment_id,
    user_id,
    created_at
FROM segment_members
WHERE segment_id = $1 AND user_id = $2
LIMIT 1
`

type GetSegmentMemberBySegmentAndUserParams struct {
	SegmentID int64 `db:"segment_id"`
	UserID    int64 `db:"user_id"`
}

func (q *Queries) GetSegmentMemberBySegmentAndUser(ctx context.Context, arg GetSegmentMemberBySegmentAndUserParams) (SegmentMember, error) {
	row := q.db.QueryRow(ctx, getSegmentMemberBySegmentAndUser, arg.SegmentID, arg.UserID)
	var i SegmentMember
	err := row.Scan(
		&i.ID,
		&i.SegmentID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getSegmentMembersBySegmentID = `-- name: GetSegmentMembersBySegmentID :many
SELECT
    id,
    segment_id,
    user_id,
    created_at
FROM segment_members
WHERE segment_id = $1
ORDER BY id
`

func (q *Queries) GetSegmentMembersBySegmentID(ctx context.Context, segmentID int64) ([]SegmentMember, error) {
	rows, err := q.db.Query(ctx, getSegmentMembersBySegmentID, segmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SegmentMember{}
	for rows.Next() {
		var i SegmentMember
		if err := rows.Scan(
			&i.ID,
			&i.SegmentID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSegmentMembersByUserID = `-- name: GetSegmentMembersByUserID :many
SELECT
    id,
    segment_id,
    user_id,
    created_at
FROM segment_members
WHERE user_id = $1
ORDER BY id
`

func (q *Queries) GetSegmentMembersByUserID(ctx context.Context, userID int64) ([]SegmentMember, error) {
	rows, err := q.db.Query(ctx, getSegmentMembersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SegmentMember{}
	for rows.Next() {
		var i SegmentMember
		if err := rows.Scan(
			&i.ID,
			&i.SegmentID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSegmentMembers = `-- name: ListSegmentMembers :many
SELECT
    id,
    segment_id,
    user_id,
    created_at
FROM segment_members
WHERE
    ($1::bigint IS NULL OR segment_id = $1) AND
    ($2::bigint IS NULL OR user_id = $2)
ORDER BY id
`

type ListSegmentMembersParams struct {
	Column1 int64 `db:"column_1"`
	Column2 int64 `db:"column_2"`
}

func (q *Queries) ListSegmentMembers(ctx context.Context, arg ListSegmentMembersParams) ([]SegmentMember, error) {
	rows, err := q.db.Query(ctx, listSegmentMembers, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SegmentMember{}
	for rows.Next() {
		var i SegmentMember
		if err := rows.Scan(
			&i.ID,
			&i.SegmentID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
