// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: staff_users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStaffUser = `-- name: CreateStaffUser :one
INSERT INTO staff_users (
    role_id,
    name,
    email,
    password_hash
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, role_id, name, email, password_hash, is_active, created_at, updated_at
`

type CreateStaffUserParams struct {
	RoleID       int64  `db:"role_id"`
	Name         string `db:"name"`
	Email        string `db:"email"`
	PasswordHash string `db:"password_hash"`
}

func (q *Queries) CreateStaffUser(ctx context.Context, arg CreateStaffUserParams) (StaffUser, error) {
	row := q.db.QueryRow(ctx, createStaffUser,
		arg.RoleID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
	)
	var i StaffUser
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffUserByEmail = `-- name: GetStaffUserByEmail :one
SELECT
    id,
    role_id,
    name,
    email,
    password_hash,
    is_active,
    created_at,
    updated_at
FROM staff_users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetStaffUserByEmail(ctx context.Context, email string) (StaffUser, error) {
	row := q.db.QueryRow(ctx, getStaffUserByEmail, email)
	var i StaffUser
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffUserByID = `-- name: GetStaffUserByID :one
SELECT
    id,
    role_id,
    name,
    email,
    password_hash,
    is_active,
    created_at,
    updated_at
FROM staff_users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetStaffUserByID(ctx context.Context, id int64) (StaffUser, error) {
	row := q.db.QueryRow(ctx, getStaffUserByID, id)
	var i StaffUser
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStaffUsers = `-- name: ListStaffUsers :many
SELECT
    id,
    role_id,
    name,
    email,
    is_active,
    created_at,
    updated_at
FROM staff_users
ORDER BY id
`

type ListStaffUsersRow struct {
	ID        int64              `db:"id"`
	RoleID    int64              `db:"role_id"`
	Name      string             `db:"name"`
	Email     string             `db:"email"`
	IsActive  bool               `db:"is_active"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
}

func (q *Queries) ListStaffUsers(ctx context.Context) ([]ListStaffUsersRow, error) {
	rows, err := q.db.Query(ctx, listStaffUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaffUsersRow{}
	for rows.Next() {
		var i ListStaffUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.Name,
			&i.Email,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStaffPassword = `-- name: UpdateStaffPassword :exec
UPDATE staff_users
SET
    password_hash = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateStaffPasswordParams struct {
	ID           int64  `db:"id"`
	PasswordHash string `db:"password_hash"`
}

func (q *Queries) UpdateStaffPassword(ctx context.Context, arg UpdateStaffPasswordParams) error {
	_, err := q.db.Exec(ctx, updateStaffPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateStaffStatus = `-- name: UpdateStaffStatus :exec
UPDATE staff_users
SET
    is_active = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateStaffStatusParams struct {
	ID       int64 `db:"id"`
	IsActive bool  `db:"is_active"`
}

func (q *Queries) UpdateStaffStatus(ctx context.Context, arg UpdateStaffStatusParams) error {
	_, err := q.db.Exec(ctx, updateStaffStatus, arg.ID, arg.IsActive)
	return err
}
