// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTemplates = `-- name: CountTemplates :one

SELECT COUNT(*)
FROM templates
`

// ==========================================
// COUNT
// ==========================================
func (q *Queries) CountTemplates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTemplates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTemplate = `-- name: CreateTemplate :one

INSERT INTO templates (
    name,
    title_template,
    body_template,
    created_by
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING
    id,
    name,
    title_template,
    body_template,
    created_by,
    is_active,
    created_at,
    updated_at
`

type CreateTemplateParams struct {
	Name          string `db:"name"`
	TitleTemplate string `db:"title_template"`
	BodyTemplate  string `db:"body_template"`
	CreatedBy     int64  `db:"created_by"`
}

type CreateTemplateRow struct {
	ID            int64              `db:"id"`
	Name          string             `db:"name"`
	TitleTemplate string             `db:"title_template"`
	BodyTemplate  string             `db:"body_template"`
	CreatedBy     int64              `db:"created_by"`
	IsActive      bool               `db:"is_active"`
	CreatedAt     pgtype.Timestamptz `db:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at"`
}

// ==========================================
// CREATE
// ==========================================
func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (CreateTemplateRow, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.Name,
		arg.TitleTemplate,
		arg.BodyTemplate,
		arg.CreatedBy,
	)
	var i CreateTemplateRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TitleTemplate,
		&i.BodyTemplate,
		&i.CreatedBy,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :exec

DELETE
FROM templates
WHERE id = $1
`

// ==========================================
// DELETE
// ==========================================
func (q *Queries) DeleteTemplate(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTemplate, id)
	return err
}

const existsTemplateByName = `-- name: ExistsTemplateByName :one

SELECT EXISTS (
    SELECT 1
    FROM templates
    WHERE name = $1
)
`

// ==========================================
// EXISTS
// ==========================================
func (q *Queries) ExistsTemplateByName(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, existsTemplateByName, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getTemplateByID = `-- name: GetTemplateByID :one

SELECT
    id,
    name,
    title_template,
    body_template,
    created_by,
    is_active,
    created_at,
    updated_at
FROM templates
WHERE id = $1
LIMIT 1
`

type GetTemplateByIDRow struct {
	ID            int64              `db:"id"`
	Name          string             `db:"name"`
	TitleTemplate string             `db:"title_template"`
	BodyTemplate  string             `db:"body_template"`
	CreatedBy     int64              `db:"created_by"`
	IsActive      bool               `db:"is_active"`
	CreatedAt     pgtype.Timestamptz `db:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at"`
}

// ==========================================
// GET
// ==========================================
func (q *Queries) GetTemplateByID(ctx context.Context, id int64) (GetTemplateByIDRow, error) {
	row := q.db.QueryRow(ctx, getTemplateByID, id)
	var i GetTemplateByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TitleTemplate,
		&i.BodyTemplate,
		&i.CreatedBy,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByName = `-- name: GetTemplateByName :one
SELECT
    id,
    name,
    title_template,
    body_template,
    created_by,
    is_active,
    created_at,
    updated_at
FROM templates
WHERE name = $1
LIMIT 1
`

type GetTemplateByNameRow struct {
	ID            int64              `db:"id"`
	Name          string             `db:"name"`
	TitleTemplate string             `db:"title_template"`
	BodyTemplate  string             `db:"body_template"`
	CreatedBy     int64              `db:"created_by"`
	IsActive      bool               `db:"is_active"`
	CreatedAt     pgtype.Timestamptz `db:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at"`
}

func (q *Queries) GetTemplateByName(ctx context.Context, name string) (GetTemplateByNameRow, error) {
	row := q.db.QueryRow(ctx, getTemplateByName, name)
	var i GetTemplateByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TitleTemplate,
		&i.BodyTemplate,
		&i.CreatedBy,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many

SELECT
    t.id,
    t.name,
    t.title_template,
    t.body_template,
    t.is_active,
    su.name AS created_by_name,
    t.created_at,
    t.updated_at
FROM templates t
JOIN staff_users su
    ON su.id = t.created_by
ORDER BY t.name
LIMIT $2
OFFSET $1
`

type ListTemplatesParams struct {
	Offset int32 `db:"offset"`
	Limit  int32 `db:"limit"`
}

type ListTemplatesRow struct {
	ID            int64              `db:"id"`
	Name          string             `db:"name"`
	TitleTemplate string             `db:"title_template"`
	BodyTemplate  string             `db:"body_template"`
	IsActive      bool               `db:"is_active"`
	CreatedByName string             `db:"created_by_name"`
	CreatedAt     pgtype.Timestamptz `db:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at"`
}

// ==========================================
// LIST
// ==========================================
func (q *Queries) ListTemplates(ctx context.Context, arg ListTemplatesParams) ([]ListTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listTemplates, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTemplatesRow{}
	for rows.Next() {
		var i ListTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TitleTemplate,
			&i.BodyTemplate,
			&i.IsActive,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTemplates = `-- name: SearchTemplates :many

SELECT
    t.id,
    t.name,
    t.title_template,
    t.body_template,
    t.is_active,
    su.name AS created_by_name,
    t.created_at,
    t.updated_at
FROM templates t
JOIN staff_users su
    ON su.id = t.created_by
WHERE
    t.name ILIKE '%' || $1 || '%'
ORDER BY t.name
LIMIT $3
OFFSET $2
`

type SearchTemplatesParams struct {
	Keyword pgtype.Text `db:"keyword"`
	Offset  int32       `db:"offset"`
	Limit   int32       `db:"limit"`
}

type SearchTemplatesRow struct {
	ID            int64              `db:"id"`
	Name          string             `db:"name"`
	TitleTemplate string             `db:"title_template"`
	BodyTemplate  string             `db:"body_template"`
	IsActive      bool               `db:"is_active"`
	CreatedByName string             `db:"created_by_name"`
	CreatedAt     pgtype.Timestamptz `db:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at"`
}

// ==========================================
// SEARCH
// ==========================================
func (q *Queries) SearchTemplates(ctx context.Context, arg SearchTemplatesParams) ([]SearchTemplatesRow, error) {
	rows, err := q.db.Query(ctx, searchTemplates, arg.Keyword, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTemplatesRow{}
	for rows.Next() {
		var i SearchTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TitleTemplate,
			&i.BodyTemplate,
			&i.IsActive,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :exec

UPDATE templates
SET
    name = $1,
    title_template = $2,
    body_template = $3,
    updated_at = NOW()
WHERE id = $4
`

type UpdateTemplateParams struct {
	Name          string `db:"name"`
	TitleTemplate string `db:"title_template"`
	BodyTemplate  string `db:"body_template"`
	ID            int64  `db:"id"`
}

// ==========================================
// UPDATE
// ==========================================
func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) error {
	_, err := q.db.Exec(ctx, updateTemplate,
		arg.Name,
		arg.TitleTemplate,
		arg.BodyTemplate,
		arg.ID,
	)
	return err
}

const updateTemplateStatus = `-- name: UpdateTemplateStatus :exec
UPDATE templates
SET
    is_active = $1,
    updated_at = NOW()
WHERE id = $2
`

type UpdateTemplateStatusParams struct {
	IsActive bool  `db:"is_active"`
	ID       int64 `db:"id"`
}

func (q *Queries) UpdateTemplateStatus(ctx context.Context, arg UpdateTemplateStatusParams) error {
	_, err := q.db.Exec(ctx, updateTemplateStatus, arg.IsActive, arg.ID)
	return err
}
