// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package sqlc

import (
	"context"
)

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (
    name,
    title_template,
    body_template,
    variables,
    created_by,
    is_active
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, name, title_template, body_template, variables, created_by, is_active, created_at, updated_at
`

type CreateTemplateParams struct {
	Name          string `db:"name"`
	TitleTemplate string `db:"title_template"`
	BodyTemplate  string `db:"body_template"`
	Variables     []byte `db:"variables"`
	CreatedBy     int64  `db:"created_by"`
	IsActive      bool   `db:"is_active"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.Name,
		arg.TitleTemplate,
		arg.BodyTemplate,
		arg.Variables,
		arg.CreatedBy,
		arg.IsActive,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TitleTemplate,
		&i.BodyTemplate,
		&i.Variables,
		&i.CreatedBy,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates
WHERE id = $1
`

func (q *Queries) DeleteTemplate(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTemplate, id)
	return err
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT
    id,
    name,
    title_template,
    body_template,
    variables,
    created_by,
    is_active,
    created_at,
    updated_at
FROM templates
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTemplateByID(ctx context.Context, id int64) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByID, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TitleTemplate,
		&i.BodyTemplate,
		&i.Variables,
		&i.CreatedBy,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByName = `-- name: GetTemplateByName :one
SELECT
    id,
    name,
    title_template,
    body_template,
    variables,
    created_by,
    is_active,
    created_at,
    updated_at
FROM templates
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetTemplateByName(ctx context.Context, name string) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByName, name)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TitleTemplate,
		&i.BodyTemplate,
		&i.Variables,
		&i.CreatedBy,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT
    id,
    name,
    title_template,
    body_template,
    variables,
    created_by,
    is_active,
    created_at,
    updated_at
FROM templates
WHERE
    ($1::boolean IS NULL OR is_active = $1) AND
    ($2::bigint IS NULL OR created_by = $2)
ORDER BY id
`

type ListTemplatesParams struct {
	Column1 bool  `db:"column_1"`
	Column2 int64 `db:"column_2"`
}

func (q *Queries) ListTemplates(ctx context.Context, arg ListTemplatesParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplates, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TitleTemplate,
			&i.BodyTemplate,
			&i.Variables,
			&i.CreatedBy,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :exec
UPDATE templates
SET
    name = $2,
    title_template = $3,
    body_template = $4,
    variables = $5,
    is_active = $6,
    updated_at = NOW()
WHERE id = $1
`

type UpdateTemplateParams struct {
	ID            int64  `db:"id"`
	Name          string `db:"name"`
	TitleTemplate string `db:"title_template"`
	BodyTemplate  string `db:"body_template"`
	Variables     []byte `db:"variables"`
	IsActive      bool   `db:"is_active"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) error {
	_, err := q.db.Exec(ctx, updateTemplate,
		arg.ID,
		arg.Name,
		arg.TitleTemplate,
		arg.BodyTemplate,
		arg.Variables,
		arg.IsActive,
	)
	return err
}

const updateTemplateActive = `-- name: UpdateTemplateActive :exec
UPDATE templates
SET
    is_active = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateTemplateActiveParams struct {
	ID       int64 `db:"id"`
	IsActive bool  `db:"is_active"`
}

func (q *Queries) UpdateTemplateActive(ctx context.Context, arg UpdateTemplateActiveParams) error {
	_, err := q.db.Exec(ctx, updateTemplateActive, arg.ID, arg.IsActive)
	return err
}
