// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upload_batch_rows.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUploadBatchRows = `-- name: CountUploadBatchRows :one

SELECT COUNT(*)
FROM upload_batch_rows
WHERE batch_id = $1
`

// ==========================================
// COUNT
// ==========================================
func (q *Queries) CountUploadBatchRows(ctx context.Context, batchID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUploadBatchRows, batchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUploadBatchRow = `-- name: CreateUploadBatchRow :one

INSERT INTO upload_batch_rows (
    batch_id,
    external_id,
    is_valid,
    error_message
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING
    id,
    batch_id,
    external_id,
    is_valid,
    error_message,
    created_at
`

type CreateUploadBatchRowParams struct {
	BatchID      int64       `db:"batch_id"`
	ExternalID   string      `db:"external_id"`
	IsValid      bool        `db:"is_valid"`
	ErrorMessage pgtype.Text `db:"error_message"`
}

// ==========================================
// CREATE
// ==========================================
func (q *Queries) CreateUploadBatchRow(ctx context.Context, arg CreateUploadBatchRowParams) (UploadBatchRow, error) {
	row := q.db.QueryRow(ctx, createUploadBatchRow,
		arg.BatchID,
		arg.ExternalID,
		arg.IsValid,
		arg.ErrorMessage,
	)
	var i UploadBatchRow
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.ExternalID,
		&i.IsValid,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listUploadBatchRows = `-- name: ListUploadBatchRows :many

SELECT
    id,
    batch_id,
    external_id,
    is_valid,
    error_message,
    created_at
FROM upload_batch_rows
WHERE batch_id = $1
ORDER BY created_at
LIMIT $3
OFFSET $2
`

type ListUploadBatchRowsParams struct {
	BatchID int64 `db:"batch_id"`
	Offset  int32 `db:"offset"`
	Limit   int32 `db:"limit"`
}

// ==========================================
// LIST
// ==========================================
func (q *Queries) ListUploadBatchRows(ctx context.Context, arg ListUploadBatchRowsParams) ([]UploadBatchRow, error) {
	rows, err := q.db.Query(ctx, listUploadBatchRows, arg.BatchID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UploadBatchRow{}
	for rows.Next() {
		var i UploadBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.ExternalID,
			&i.IsValid,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
