// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upload_batches.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUploadBatches = `-- name: CountUploadBatches :one

SELECT COUNT(*)
FROM upload_batches
`

// ==========================================
// COUNT
// ==========================================
func (q *Queries) CountUploadBatches(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUploadBatches)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUploadBatch = `-- name: CreateUploadBatch :one

INSERT INTO upload_batches (
    uploaded_by,
    original_filename,
    total_rows,
    valid_rows,
    invalid_rows
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING
    id,
    uploaded_by,
    original_filename,
    total_rows,
    valid_rows,
    invalid_rows,
    created_at
`

type CreateUploadBatchParams struct {
	UploadedBy       int64  `db:"uploaded_by"`
	OriginalFilename string `db:"original_filename"`
	TotalRows        int32  `db:"total_rows"`
	ValidRows        int32  `db:"valid_rows"`
	InvalidRows      int32  `db:"invalid_rows"`
}

// ==========================================
// CREATE
// ==========================================
func (q *Queries) CreateUploadBatch(ctx context.Context, arg CreateUploadBatchParams) (UploadBatch, error) {
	row := q.db.QueryRow(ctx, createUploadBatch,
		arg.UploadedBy,
		arg.OriginalFilename,
		arg.TotalRows,
		arg.ValidRows,
		arg.InvalidRows,
	)
	var i UploadBatch
	err := row.Scan(
		&i.ID,
		&i.UploadedBy,
		&i.OriginalFilename,
		&i.TotalRows,
		&i.ValidRows,
		&i.InvalidRows,
		&i.CreatedAt,
	)
	return i, err
}

const getUploadBatchByID = `-- name: GetUploadBatchByID :one

SELECT
    id,
    uploaded_by,
    original_filename,
    total_rows,
    valid_rows,
    invalid_rows,
    created_at
FROM upload_batches
WHERE id = $1
LIMIT 1
`

// ==========================================
// GET
// ==========================================
func (q *Queries) GetUploadBatchByID(ctx context.Context, id int64) (UploadBatch, error) {
	row := q.db.QueryRow(ctx, getUploadBatchByID, id)
	var i UploadBatch
	err := row.Scan(
		&i.ID,
		&i.UploadedBy,
		&i.OriginalFilename,
		&i.TotalRows,
		&i.ValidRows,
		&i.InvalidRows,
		&i.CreatedAt,
	)
	return i, err
}

const listUploadBatches = `-- name: ListUploadBatches :many

SELECT
    ub.id,
    ub.original_filename,
    ub.total_rows,
    ub.valid_rows,
    ub.invalid_rows,
    su.name AS uploaded_by_name,
    ub.created_at
FROM upload_batches ub
JOIN staff_users su
    ON su.id = ub.uploaded_by
ORDER BY ub.created_at DESC
LIMIT $2
OFFSET $1
`

type ListUploadBatchesParams struct {
	Offset int32 `db:"offset"`
	Limit  int32 `db:"limit"`
}

type ListUploadBatchesRow struct {
	ID               int64              `db:"id"`
	OriginalFilename string             `db:"original_filename"`
	TotalRows        int32              `db:"total_rows"`
	ValidRows        int32              `db:"valid_rows"`
	InvalidRows      int32              `db:"invalid_rows"`
	UploadedByName   string             `db:"uploaded_by_name"`
	CreatedAt        pgtype.Timestamptz `db:"created_at"`
}

// ==========================================
// LIST
// ==========================================
func (q *Queries) ListUploadBatches(ctx context.Context, arg ListUploadBatchesParams) ([]ListUploadBatchesRow, error) {
	rows, err := q.db.Query(ctx, listUploadBatches, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUploadBatchesRow{}
	for rows.Next() {
		var i ListUploadBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginalFilename,
			&i.TotalRows,
			&i.ValidRows,
			&i.InvalidRows,
			&i.UploadedByName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
