// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upload_batch_rows.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUploadBatchRow = `-- name: CreateUploadBatchRow :one
INSERT INTO upload_batch_rows (
    batch_id,
    external_id,
    is_valid,
    error_message
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, batch_id, external_id, is_valid, error_message, created_at
`

type CreateUploadBatchRowParams struct {
	BatchID      int64       `db:"batch_id"`
	ExternalID   string      `db:"external_id"`
	IsValid      bool        `db:"is_valid"`
	ErrorMessage pgtype.Text `db:"error_message"`
}

func (q *Queries) CreateUploadBatchRow(ctx context.Context, arg CreateUploadBatchRowParams) (UploadBatchRow, error) {
	row := q.db.QueryRow(ctx, createUploadBatchRow,
		arg.BatchID,
		arg.ExternalID,
		arg.IsValid,
		arg.ErrorMessage,
	)
	var i UploadBatchRow
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.ExternalID,
		&i.IsValid,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUploadBatchRow = `-- name: DeleteUploadBatchRow :exec
DELETE FROM upload_batch_rows
WHERE id = $1
`

func (q *Queries) DeleteUploadBatchRow(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUploadBatchRow, id)
	return err
}

const deleteUploadBatchRowsByBatch = `-- name: DeleteUploadBatchRowsByBatch :exec
DELETE FROM upload_batch_rows
WHERE batch_id = $1
`

func (q *Queries) DeleteUploadBatchRowsByBatch(ctx context.Context, batchID int64) error {
	_, err := q.db.Exec(ctx, deleteUploadBatchRowsByBatch, batchID)
	return err
}

const getUploadBatchRowByID = `-- name: GetUploadBatchRowByID :one
SELECT
    id,
    batch_id,
    external_id,
    is_valid,
    error_message,
    created_at
FROM upload_batch_rows
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUploadBatchRowByID(ctx context.Context, id int64) (UploadBatchRow, error) {
	row := q.db.QueryRow(ctx, getUploadBatchRowByID, id)
	var i UploadBatchRow
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.ExternalID,
		&i.IsValid,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getUploadBatchRowsByBatchID = `-- name: GetUploadBatchRowsByBatchID :many
SELECT
    id,
    batch_id,
    external_id,
    is_valid,
    error_message,
    created_at
FROM upload_batch_rows
WHERE batch_id = $1
ORDER BY id
`

func (q *Queries) GetUploadBatchRowsByBatchID(ctx context.Context, batchID int64) ([]UploadBatchRow, error) {
	rows, err := q.db.Query(ctx, getUploadBatchRowsByBatchID, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UploadBatchRow{}
	for rows.Next() {
		var i UploadBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.ExternalID,
			&i.IsValid,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUploadBatchRowsByExternalID = `-- name: GetUploadBatchRowsByExternalID :many
SELECT
    id,
    batch_id,
    external_id,
    is_valid,
    error_message,
    created_at
FROM upload_batch_rows
WHERE external_id = $1
ORDER BY batch_id DESC
`

func (q *Queries) GetUploadBatchRowsByExternalID(ctx context.Context, externalID string) ([]UploadBatchRow, error) {
	rows, err := q.db.Query(ctx, getUploadBatchRowsByExternalID, externalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UploadBatchRow{}
	for rows.Next() {
		var i UploadBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.ExternalID,
			&i.IsValid,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadBatchRows = `-- name: ListUploadBatchRows :many
SELECT
    id,
    batch_id,
    external_id,
    is_valid,
    error_message,
    created_at
FROM upload_batch_rows
WHERE
    ($1::bigint IS NULL OR batch_id = $1) AND
    ($2::boolean IS NULL OR is_valid = $2)
ORDER BY id
`

type ListUploadBatchRowsParams struct {
	Column1 int64 `db:"column_1"`
	Column2 bool  `db:"column_2"`
}

func (q *Queries) ListUploadBatchRows(ctx context.Context, arg ListUploadBatchRowsParams) ([]UploadBatchRow, error) {
	rows, err := q.db.Query(ctx, listUploadBatchRows, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UploadBatchRow{}
	for rows.Next() {
		var i UploadBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.ExternalID,
			&i.IsValid,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUploadBatchRow = `-- name: UpdateUploadBatchRow :exec
UPDATE upload_batch_rows
SET
    is_valid = $2,
    error_message = $3
WHERE id = $1
`

type UpdateUploadBatchRowParams struct {
	ID           int64       `db:"id"`
	IsValid      bool        `db:"is_valid"`
	ErrorMessage pgtype.Text `db:"error_message"`
}

func (q *Queries) UpdateUploadBatchRow(ctx context.Context, arg UpdateUploadBatchRowParams) error {
	_, err := q.db.Exec(ctx, updateUploadBatchRow, arg.ID, arg.IsValid, arg.ErrorMessage)
	return err
}
